#!/bin/sh

set -o nounset

. /etc/rc.local.conf

first_video_dir=`echo $vdr_videodirs | cut -d ' ' -f 1`
conf_tar=$first_video_dir/vdr_conf.tar

usage_and_exit () {
    echo "$0 guarda o recupera la configuración de VDR en un archivo tar dentro del directorio de grabaciones"
    echo "Uso: $0 [save|load|info]"
    exit 1
}

if [ ! $# -eq 1 ]; then
    usage_and_exit
fi

if [ ! -d "$first_video_dir" ]; then
    echo "No existe el directorio de grabaciones $first_video_dir"
    echo "Revise la configuración en:"
    echo "   Configurar firmware Gigaset 7x0 > Configuración de directorios > Directorio de grabaciones"
    exit 2
fi

case $1 in
    save)
	if [ ! -w $first_video_dir ]; then
	    echo "No se puede escribir en el directorio de grabaciones $first_video_dir"
	    echo "Revise la configuración en:"
	    echo "   Configurar firmware m7x0 > Configuración de discos > Directorio de grabaciones"
	    exit 3
	else
	    tar -cf $conf_tar $vdr_confdir/setup.conf $vdr_confdir/svdrphosts.conf $vdr_confdir/timers.conf $vdr_confdir/channels.conf $vdr_confdir/plugins/streamdevhosts.conf $vdr_confdir/plugins/epgsearch/*.conf /etc/rc.local.conf /etc/resolv.conf /etc/rc.conf /etc/webif.conf /etc/fstab 2> /tmp/tar_backup.$$.err
	    if [ $? -eq 0 ]; then
		echo "Configuración guardada correctamente en $conf_tar"
		rm /tmp/tar_backup.$$.err
	    else
		cat /tmp/tar_backup.$$.err
		echo "Ocurrió un error al intentar guardar la configuración"
		rm /tmp/tar_backup.$$.err
		exit 4
	    fi
	fi
	;;
    load)
	if [ ! -r $conf_tar ]; then
	    echo "No existe el archivo $conf_tar del que recuperar la configuración."
	    echo "Ha de guardar la configuración primero."
	    exit 5
	else

	    if [ -f /var/run/runvdr.pid ]; then
		echo "VDR se reiniciará ahora para aplicar la nueva configuración"

		# No se puede imprimir nada a partir de aqui o recibiremos SIGPIPE
		{
		    kill-vdr

		    tar -C / -xf $conf_tar
		    
		    if [ ! $? -eq 0 ]; then
			logger -s user.warning "Ocurrió un error al intentar recuperar la configuración"
		    fi
		    
		    start-vdr
		} > /dev/null 2>&1 &
		
	    else
		tar -C / -xf $conf_tar
	    fi
	fi

	;;
    info)
	if [ ! -r $conf_tar ]; then
	    echo "No existe el archivo $conf_tar del que recuperar la configuración"
	    exit 7
	else
	    echo "Configuración guardada en:"
	    ls -lh $conf_tar
	    echo
	    echo "Contenido del archivo:"
	    tar -tf $conf_tar	
	fi
	;;
    *)
    usage_and_exit
esac
