#!/bin/ash
KILL="killall -15"
VDR_FLAGS="-c ${vdr_confdir} -L /var/vdr/lib -v /var/vdr/video0 -s \
  ${vdr_shutdown}"

mkdir -p /var/vdr
mkdir -p /var/vdr/lib

my_pid=$$
echo $my_pid > /var/run/runvdr.pid

# EPG Data

if [ "${vdr_epgfile}" != "-" ] ; then
    if [ "${vdr_epgdirect}" = "NO" ] ; then
        [ -f ${vdr_epgfile} ] && mv ${vdr_epgfile} /var/vdr/epg.data
        VDR_EPGOPT="-E /var/vdr/epg.data"
    else
# Don't change this again. Links to direct epg-file not working 
# as VDR writes to /var/vdr/epg.data.$$$ and do 
# rename("/var/vdr/epg.data.$$$","/var/vdr/epg.data"); (AK)
        VDR_EPGOPT="-E ${vdr_epgfile}"
    fi
else
    VDR_EPGOPT="-E-"
fi

# Video dirs

if [ X"${vdr_videodirs}" != X"" ] ; then
    vdirn=0
    for vdir in ${vdr_videodirs} ; do
        ln -snf ${vdir} /var/vdr/video${vdirn}
        vdirn=$(( ${vdirn} + 1 ))
    done
else
    # fallback no video dir defined
    mkdir -p /var/vdr/video.flash
    ln -snf /var/vdr/video.flash /var/vdr/video0
fi

while (true) do
    rm -f /var/vdr/lib/*
    for plug in `find ${vdr_plugindirs} -name "libvdr*.so*" -type f`; do
 	ln -snf ${plug} /var/vdr/lib/`basename ${plug}`
    done
    ${vdr_bin} ${VDR_EPGOPT} ${VDR_FLAGS} ${vdr_pluginopts} ${vdr_stumode} ${vdr_options}
    if [ $? != 1 ]; then
        break
    fi
    echo "restarting VDR"
    $KILL $vdr_bin
    sleep 1
done

rm -f /var/run/runvdr.pid
exit 0