#!/bin/ash

if [ X"${OSDLOG}" = X"YES" ]; then
    source /etc/rc.debug
fi

[ -f /etc/rc.conf ] && source /etc/rc.conf

if [ X"${syslogd_flags}" != X"NO" ]; then
    mv /rw-flash/log/messages* /var/log
    echo -n "starting syslogd ... "
    syslogd ${syslogd_flags}
    echo "Done"
fi

echo -n "loading modules ... "
[ -f /etc/rc.modules ] && ash /etc/rc.modules
echo "Done";

if [ X"${pic_tool_flags}" != X"NO" ]; then
    echo -n "execute pic_tool ... "
    pic_tool ${pic_tool_flags}
    echo "Done"
fi

echo -n "starting loopback"
ifconfig lo 127.0.0.1
echo "Done"

if [ X"${lircd_flags}" != X"NO" ]; then
    echo "lircd daemon";		lircd ${lircd_flags}
fi

[ -f /etc/rc.local ] && ash /etc/rc.local

exit 0
