/*
  	WARNING: automatically generated content. Changes will get lost!

    If this file is 'i18n-generated.h' then it *really* is automatically
	generated.
    If this file is 'i18n-template.h' then it is the base for the
    autogeneration of the other file.

*/

const tI18nPhrase Phrases[] = {
// START I18N - automatically generated by pot2i18n.pl
  { "Channel (press OK): ",
    "Sender (OK drücken): ",
    "",
    "Canale (premi OK): ",
    "",
    "Sender (Prima OK): ",
    "Chaine (Appuyer sur OK): ",
    "",
    "Kanava (paina OK):",
    "",
    "Canal (pulse OK):",
    "",
    "",
    "",
    "",
    "Canal (premi OK):",
#if VDRVERSNUM >= 10302
    "ºÐÝÐÛ (½ÐÖÜØâÕ ¾º)",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Page",
    "Seite",
    "",
    "Pagina",
    "",
    "Página",
    "Page",
    "",
    "Sivua",
    "",
    "Página",
    "",
    "",
    "",
    "",
    "Pàgina",
#if VDRVERSNUM >= 10302
    "ÁâàÐÝØæÐ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "not found until now, searching",
    "nicht gefunden",
    "",
    "non trovata",
    "",
    "Não encontrado",
    "pas trouvÃ©",
    "",
    "ei lÃ¶ydy",
    "",
    "no encontrada todavía, buscando ...",
    "",
    "",
    "",
    "",
    "no trobada",
#if VDRVERSNUM >= 10302
    "ÝÕ ÝÐÙÔÕÝÐ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Displays teletext on the OSD",
    "Zeigt den Videotext auf dem OSD an",
    "",
    "Mostra il teletext in OSD",
    "",
    "Mostra o teletexto no OSD",
    "Affiche le tÃ©lÃ©texte sur l'OSD",
    "",
    "Teksti-TV (OSD)",
    "",
    "Muestra el teletexto en el OSD",
    "",
    "",
    "",
    "",
    "Visualitza el teletext en l'OSD",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ× âÕÛÕâÕÚáâÐ Ò OSD",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Teletext",
    "Videotext",
    "",
    "Teletext",
    "",
    "Teletexto",
    "Teletexte",
    "",
    "Teksti-TV",
    "",
    "Teletexto",
    "",
    "",
    "",
    "",
    "Teletext",
#if VDRVERSNUM >= 10302
    "ÂÕÛÕâÕÚáâ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Zoom",
    "Vergrößern",
    "",
    "Ingrandisci",
    "",
    "Zoom",
    "Zoom",
    "",
    "Suurenna",
    "",
    "Zoom",
    "",
    "",
    "",
    "",
    "Zoom",
#if VDRVERSNUM >= 10302
    "ãÒÕÛØçØâì",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Half page",
    "Halbe Seite",
    "",
    "MetÃ  pagina",
    "",
    "Meia Página",
    "Demi-Page",
    "",
    "Puolikas sivu",
    "",
    "Media página",
    "",
    "",
    "",
    "",
    "Mitja pàgina",
#if VDRVERSNUM >= 10302
    "ßÞÛ-áâàÐÝØæë",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Change channel",
    "Kanal wechseln",
    "",
    "Cambia canale",
    "",
    "Mudar canal",
    "Changer la chaÃ®ne",
    "",
    "Vaihda kanavaa",
    "",
    "Cambiar canal",
    "",
    "",
    "",
    "",
    "Canvi cadena",
#if VDRVERSNUM >= 10302
    "ßÕàÕÚÛîçØâì ÚÐÝÐÛ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Switch background",
    "Hintergrund ändern",
    "",
    "Cambia sfondo",
    "",
    "Mudar fundo",
    "Change le fond d'Ã©cran",
    "",
    "Vaihda tausta",
    "",
    "Cambiar el fondo",
    "",
    "",
    "",
    "",
    "Canvia el fons",
#if VDRVERSNUM >= 10302
    "¿ÕàÕÚÛîçØâì äÞÝ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Jump to...",
    "Springe zu...",
    "",
    "Vai a...",
    "",
    "Ir para",
    "Aller Ã ...",
    "",
    "Siirry sivulle...",
    "",
    "Saltar a...",
    "",
    "",
    "",
    "",
    "Salta a...",
#if VDRVERSNUM >= 10302
    "ßÕàÕÙâØ Ú...",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Background transparency",
    "Hintergrund-Transparenz",
    "",
    "Trasparenza sfondo",
    "",
    "Transparência do Fundo",
    "Fond transparent",
    "",
    "Taustan lÃ¤pinÃ¤kyvyys",
    "",
    "Transparencia del fondo",
    "",
    "",
    "",
    "",
    "Transparència del fons",
#if VDRVERSNUM >= 10302
    "¿àÞ×àÐçÝÞáâì äÞÝÐ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show clock",
    "Uhr anzeigen",
    "",
    "Mostra orologio",
    "",
    "Mostrar Relógio",
    "Afficher l'heure",
    "",
    "NÃ¤ytÃ¤ kello",
    "",
    "Mostrar la hora",
    "",
    "",
    "",
    "",
    "Visualitza l'hora",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì çÐáë",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Auto-update pages",
    "Seiten aktualisieren",
    "",
    "Aggiorn. automatico pagine",
    "",
    "Auto actualizar páginas",
    "Mise Ã  jour des pages",
    "",
    "Automaattinen sivupÃ¤ivitys",
    "",
    "Actualización páginas automática",
    "",
    "",
    "",
    "",
    "Actualització pàgines automàtica",
#if VDRVERSNUM >= 10302
    "°ÒâÞÞÑÝÞÒÛÕÝØÕ áâàÐÝØæ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "OSD height",
    "OSD-Höhe",
    "",
    "Altezza OSD",
    "",
    "Altura do OSD",
    "Hauteur OSD",
    "",
    "Korkeus",
    "",
    "Altura OSD",
    "",
    "",
    "",
    "",
    "Altura OSD",
#if VDRVERSNUM >= 10302
    "²ëáÞâÐ ÜÕÝî",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "OSD width",
    "OSD-Breite",
    "",
    "Larghezza OSD",
    "",
    "Largura do OSD",
    "Largeur OSD",
    "",
    "Leveys",
    "",
    "Anchura OSD",
    "",
    "",
    "",
    "",
    "Amplària OSD",
#if VDRVERSNUM >= 10302
    "ÈØàØÝÐ ÜÕÝî",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "OSD horizontal align",
    "OSD horizontale Anordnung",
    "",
    "Allineamento orizzontale OSD",
    "",
    "Alinhamento Horizontal do OSD",
    "Alignement horizontal de l'OSD",
    "",
    "Pystykeskitys",
    "",
    "OSD alineación horizontal",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "³ÞàØ×ÞÝâÐÛìÝÞÕ ßÞÛÞÖÕÝØÕ OSD",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "OSD vertical align",
    "OSD vertikale Anordnung",
    "",
    "Allineamento verticale OSD",
    "",
    "Alinhamento Vertical do OSD",
    "Alignement vertical de l'OSD",
    "",
    "Vaakakeskitys",
    "",
    "OSD alineación vertical",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "²ÕàâØÚÐÛìÝÞÕ ßÞÛÞÖÕÝØÕ OSD",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Key bindings",
    "Tastenzuweisung",
    "",
    "Tasti associati",
    "",
    "Tecla alocada",
    "Attribution des touches",
    "",
    "NÃ¤ppÃ¤intoiminnot",
    "",
    "Asignación de botones",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿àØÒï×ÚÐ ÚÝÞßÞÚ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Page number",
    "  Seitenzahl",
    "",
    "  Numero pagina",
    "",
    "  Número de Página",
    "  Nombre de pages",
    "",
    "  Sivunumero",
    "",
    "  Número de página",
    "",
    "",
    "",
    "",
    "  Nombre de pàgina",
#if VDRVERSNUM >= 10302
    "  ½ÞÜÕà áâàÐÝØæë",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
// END I18N - automatically generated by pot2i18n.pl
  { NULL }
};
