/*
  	WARNING: automatically generated content. Changes will get lost!

    If this file is 'i18n-generated.h' then it *really* is automatically
	generated.
    If this file is 'i18n-template.h' then it is the base for the
    autogeneration of the other file.

*/

const tI18nPhrase Phrases[] = {
// START I18N - automatically generated by pot2i18n.pl
  { "Configure channels to be scraped",
    "Kanäle zum scrapen festlegen",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Configurar canales a obtener",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Trigger scraping Video Directory",
    "Scrapen des Video Verzeichnisses starten",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Obtener del directorio de vídeo",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Trigger EPG scraping",
    "EPG Scraping starten",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Obtener de la EPG",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Enable Debug Logging",
    "Debug Logging aktivieren",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Registro de depuración",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "don't scrap",
    "nicht scrapen",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "no obtener",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "scrap",
    "scrapen",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "obtener",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "en_US",
    "de_DE",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "es_ES",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
// END I18N - automatically generated by pot2i18n.pl
  { NULL }
};
