#!/bin/ash

source /etc/rc.local.conf

if [ X"${bootmenu_start}" != X"NO" ] ; then
    echo $1 >/etc/bootmenu/next_alarm
fi

if [ $1 -eq 0 ] ; then
    /usr/sbin/pic_tool alarm clear
else
    /usr/sbin/pic_tool alarm set $(( $1 - ${vdr_startup_time} ))
fi

/sbin/halt
exit 0
