#!/bin/sh

BASE='..'

echo "getting links from kernel-cvs driver"


KERNELRELEASE='2.4.21-xfs'
make clean
echo "$KERNELRELEASE" > .version

mkdir -p include/linux
ln -vs `pwd`/videodev.h include/linux/videodev.h
ln -vs `pwd`/videodev2.h include/linux/videodev2.h

for x in `find $BASE/linux/include/media/ -name "*.[hc]"` ; do
	ln -vs ../../$x include/media/`basename $x`
done

for x in `find $BASE/linux/drivers/media/dvb/ttpci/ -name "*.[hc]"` ; do
	ln -vs $x `basename $x`
done

for x in `find $BASE/linux/drivers/media/dvb/ttusb-budget/ -name "*.[hc]"` ; do
	ln -vs $x `basename $x`
done

for x in `find $BASE/linux/drivers/media/dvb/ttusb-dec/ -name "*.[hc]"` ; do
	ln -vs $x `basename $x`
done

for x in `find $BASE/linux/drivers/media/dvb/bt8xx/ -name "*.[hc]"` ; do
	ln -vs $x `basename $x`
done

for x in `find $BASE/linux/drivers/media/dvb/b2c2/ -name "*.[hc]"` ; do
	ln -vs $x `basename $x`
done

for x in `find $BASE/linux/drivers/media/dvb/cinergyT2/ -name "*.[hc]"` ; do
	ln -vs $x `basename $x`
done

for x in `find $BASE/linux/drivers/media/dvb/dvb-core/ -name "*.[hc]"` ; do
	ln -vs $x `basename $x`
done

for x in `find $BASE/linux/drivers/media/dvb/frontends -name "*.[hc]"` ; do
	ln -vs $x `basename $x`
done

for x in `find $BASE/linux/drivers/media/common -name "saa*.[hc]"` ; do
	ln -vs $x `basename $x`
done
