/*
Copyright (C) 2007 Christian Wieninger

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
Or, point your browser to http://www.gnu.org/licenses/old-licenses/gpl-2.0.html

The author can be reached at cwieninger@gmx.de

The project's page is at http://winni.vdr-developer.org/taskman
*/

/*
  	WARNING: automatically generated content. Changes will get lost!

    If this file is 'i18n-generated.h' then it *really* is automatically
	generated.
    If this file is 'i18n-template.h' then it is the base for the
    autogeneration of the other file.

*/

const tI18nPhrase Phrases[] = {
// START I18N - automatically generated by pot2i18n.pl
  { "Start",
    "Start",
    "",
    "Inizio",
    "Start menu",
    "",
    "Menue de départ",
    "",
    "Oletusnäyttö",
    "",
    "Inicio",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Current output",
    "Aktuelle Ausgabe",
    "",
    "Uscita attuale",
    "",
    "",
    "",
    "",
    "",
    "",
    "Salida actual",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Log entries",
    "Log-Einträge",
    "",
    "Valori messaggi",
    "",
    "",
    "",
    "",
    "",
    "",
    "Entradas del registro",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Hide main menu entry",
    "Hauptmenüentrag ausblenden",
    "",
    "Nascondi voce menu principale",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ocultar entrada del menú principal",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Task settings",
    "Job-Einstellungen",
    "",
    "Impostazioni attività",
    "",
    "",
    "",
    "",
    "",
    "",
    "Configurar tarea",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "End",
    "Ende",
    "",
    "Fine",
    "",
    "",
    "",
    "",
    "",
    "",
    "Final",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Start and end",
    "Start und Ende",
    "",
    "Inizio e fine",
    "Standaard",
    "",
    "Standart",
    "",
    "Vakio",
    "",
    "Inicio y final",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Description",
    "Bezeichnung",
    "",
    "Descrizione",
    "Beschrijving",
    "",
    "Description",
    "",
    "Kuvaus",
    "",
    "Descripción",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Command",
    "Befehl",
    "",
    "Comando",
    "EPG kommando's",
    "",
    "Commande EPG",
    "",
    "Komennot",
    "",
    "Comando",
    "ÅããñáöÞ",
    "Inspelning",
    "",
    "",
    "Gravar",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "Snimi",
#endif
#if VDRVERSNUM >= 10313
    "Salvesta",
#endif
#if VDRVERSNUM >= 10316
    "Optag",
#endif
#if VDRVERSNUM >= 10342
    "Nahrát",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Minute",
    "Minute",
    "",
    "Minuti",
    "",
    "",
    "",
    "",
    "",
    "",
    "Minuto",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Hour",
    "Stunde",
    "",
    "Ora",
    "",
    "",
    "",
    "",
    "",
    "",
    "Hora",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Day of week",
    "Wochentag",
    "",
    "Giorno settimana",
    "Dag van de week",
    "",
    "Jours de la semaine",
    "",
    "Viikonpäivä",
    "",
    "Día de la semana",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Day",
    "Tag",
    "",
    "Giorno",
    "",
    "",
    "",
    "",
    "Päivä",
    "",
    "Día",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Month",
    "Monat",
    "",
    "Mese",
    "",
    "",
    "",
    "",
    "",
    "",
    "Mes",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Wakeup VDR",
    "VDR wecken",
    "",
    "Risveglia VDR",
    "",
    "",
    "",
    "",
    "",
    "",
    "Despertar VDR",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Shutdown VDR",
    "VDR herunterfahren",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Apagar VDR",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "OSD announce",
    "OSD Ankündigung",
    "",
    "Annuncio OSD",
    "",
    "",
    "Annoncer à nouveau",
    "",
    "Muistuta uudelleen",
    "",
    "Aviso OSD",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Save ... logs",
    "Speichere ... Logs",
    "",
    "Salva ... messaggi",
    "",
    "",
    "",
    "",
    "",
    "",
    "Guardar ... registros",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Kill after ... minutes",
    "Abbruch nach ... Minuten",
    "",
    "Termina dopo ... minuti",
    "",
    "",
    "",
    "",
    "",
    "",
    "Detener a los ... minutos",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Next executions:",
    "Nächste Startzeiten:",
    "",
    "Prossime esecuzioni:",
    "",
    "",
    "Selection",
    "",
    "valittu",
    "",
    "Próximas ejecuciones:",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Tasks",
    "Jobs",
    "",
    "Attività",
    "",
    "",
    "",
    "",
    "",
    "",
    "Tareas",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Button$New",
    "Neu",
    "Nastavitve",
    "Nuova",
    "Instellingen",
    "Configurar",
    "Test",
    "Konfigurasjon",
    "Testaa",
    "Nastawy",
    "Nueva",
    "Ñõèìéóåéò",
    "Inställningar",
    "Configuraþie",
    "Beállítások",
    "Configuració",
#if VDRVERSNUM >= 10302
    "½ÐáâàÞÙÚÐ",
#endif
#if VDRVERSNUM >= 10307
    "Konfiguracija",
#endif
#if VDRVERSNUM >= 10313
    "Sätted",
#endif
#if VDRVERSNUM >= 10316
    "Indstillinger",
#endif
#if VDRVERSNUM >= 10342
    "Nastavení",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Button$Stop",
    "Stop",
    "Nastavitve",
    "Ferma",
    "Instellingen",
    "Configurar",
    "Test",
    "Konfigurasjon",
    "Testaa",
    "Nastawy",
    "Detener",
    "Ñõèìéóåéò",
    "Inställningar",
    "Configuraþie",
    "Beállítások",
    "Configuració",
#if VDRVERSNUM >= 10302
    "½ÐáâàÞÙÚÐ",
#endif
#if VDRVERSNUM >= 10307
    "Konfiguracija",
#endif
#if VDRVERSNUM >= 10313
    "Sätted",
#endif
#if VDRVERSNUM >= 10316
    "Indstillinger",
#endif
#if VDRVERSNUM >= 10342
    "Nastavení",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Button$Start",
    "Start",
    "Nastavitve",
    "Avvia",
    "Instellingen",
    "Configurar",
    "Test",
    "Konfigurasjon",
    "Testaa",
    "Nastawy",
    "Iniciar",
    "Ñõèìéóåéò",
    "Inställningar",
    "Configuraþie",
    "Beállítások",
    "Configuració",
#if VDRVERSNUM >= 10302
    "½ÐáâàÞÙÚÐ",
#endif
#if VDRVERSNUM >= 10307
    "Konfiguracija",
#endif
#if VDRVERSNUM >= 10313
    "Sätted",
#endif
#if VDRVERSNUM >= 10316
    "Indstillinger",
#endif
#if VDRVERSNUM >= 10342
    "Nastavení",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "%s currently running",
    "%s läuft bereits",
    "",
    "%s già in esecuzione",
    "",
    "",
    "Est déjà en cours",
    "",
    "Nyt menossa!",
    "",
    "%s ejecutándose actualmente",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Delete task?",
    "Job löschen?",
    "",
    "Eliminare attività?",
    "",
    "",
    "Effacer le modèle",
    "",
    "Poistetaanko ajastin?",
    "",
    "¿Borrar tarea?",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Abort this task?",
    "Job abbrechen?",
    "",
    "Terminare questa attività?",
    "",
    "",
    "Effectuer la recherche",
    "",
    "Suorita haku",
    "",
    "¿Cancelar esta tarea?",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Execute this task?",
    "Job starten?",
    "",
    "Eseguire questa attività?",
    "",
    "",
    "Effectuer la recherche",
    "",
    "Suorita haku",
    "",
    "¿Ejecutar esta tarea?",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Job scheduler and manager",
    "Job-Planer und -manager",
    "",
    "Pianificatore e gestore lavori",
    "",
    "",
    "",
    "",
    "",
    "",
    "Administrar y programar tareas",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Job scheduler",
    "Job-Planer",
    "",
    "Pianificatore lavori",
    "",
    "",
    "",
    "",
    "",
    "",
    "Programador de tareas",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "active",
    "aktiv",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "activa",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "'%s' still runs!",
    "'%s' läuft noch!",
    "",
    "'%s' ancora in esecuzione!",
    "",
    "",
    "",
    "",
    "",
    "",
    "¡'%s' ejecutándose todavía!",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Output",
    "Ausgabe",
    "",
    "Uscita",
    "",
    "",
    "",
    "",
    "",
    "",
    "Salida",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "%s started",
    "%s gestartet",
    "",
    "%s avviato",
    "",
    "",
    "",
    "",
    "",
    "",
    "%s iniciado",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "%s finished",
    "%s beendet",
    "",
    "%s completato",
    "",
    "",
    "",
    "",
    "",
    "",
    "%s finalizado",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
// END I18N - automatically generated by pot2i18n.pl
  { NULL }
};
