blank_issues_enabled: true
contact_links:
  - name: VDR-NG-EM international forum
    url: https://vdr-m7x0.foroactivo.com.es/international-forum-f19/
    about: International forum dedicated to the VDR-NG-EM project
  - name: VDR-NG-EM foro español
    url: https://vdr-m7x0.foroactivo.com.es/
    about: Foro español dedicado al proyecto VDR-NG-EM