#!/bin/ash
while read hd_swp_dev ignore ; do
        if [ ${hd_swp_dev} != "Filename" ] ; then
                echo "setting down swap in ${hd_swp_dev}"
                /sbin/swapoff ${hd_swp_dev}
        fi
done < /proc/swaps
