/*
  	WARNING: automatically generated content. Changes will get lost!

    If this file is 'i18n-generated.h' then it *really* is automatically
	generated.
    If this file is 'i18n-template.h' then it is the base for the
    autogeneration of the other file.

*/

const tI18nPhrase Phrases[] = {
// START I18N - automatically generated by pot2i18n.pl
  { "Channel:",
    "Kanal:",
    "",
    "Canale:",
    "Kanaal:",
    "",
    "Chaîne:",
    "",
    "Kanava:",
    "",
    "Canal:",
    "",
    "",
    "",
    "Csatorna:",
    "Canal:",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Search pattern:",
    "Suchmuster:",
    "",
    "Modello di ricerca:",
    "Zoekpatroon:",
    "",
    "Modèle de recherche",
    "",
    "Hakutapa:",
    "",
    "Buscar patrón:",
    "",
    "",
    "",
    "Keresési minta:",
    "Patró de recerca:",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Timer check",
    "Überwachung",
    "",
    "Verifica timer",
    "Monitoren",
    "",
    "Observation de la programmation",
    "",
    "Ajastimien valvonta",
    "",
    "Comprobar programación",
    "",
    "",
    "",
    "Idõzítõ ellenõrzése",
    "Verificació de temps",
#if VDRVERSNUM >= 10302
    "¿àÞÒÕàÚÐ âÐÙÜÕàÞÒ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "No timer check",
    "Ohne Überwachung",
    "",
    "Nessuna verifica timer",
    "Geen controle",
    "",
    "Sans surveillance",
    "",
    "Ei valvontaa",
    "",
    "No comprobar programación",
    "",
    "",
    "",
    "Nincs idõzítõ ellenõrzés",
    "Sense verificació de temps",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Monday",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Lunes",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Tuesday",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Martes",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Wednesday",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Miércoles",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Thursday",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Jueves",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Friday",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Viernes",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Saturday",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Sábado",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Sunday",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Domingo",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "TrueType Font",
    "TrueType Schrift",
    "",
    "Car. TrueType",
    "TrueType Font",
    "",
    "TrueType",
    "",
    "TrueType-kirjasin",
    "",
    "Fuente TrueType",
    "",
    "",
    "",
    "TrueType betûtipus",
    "Font TrueType",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Default OSD Font",
    "Std. OSD Font",
    "",
    "Car. OSD pred.",
    "Standaard OSDfont",
    "",
    "OSD standard",
    "",
    "oletuskirjasintyyppi",
    "",
    "Fuente OSD defecto",
    "",
    "",
    "",
    "Alapértelmezett OSD betûtipus",
    "Font OSD per defecte",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Default Fixed Size Font",
    "Std. Schrift mit fester Breite",
    "",
    "Car. dim. fissa pred.",
    "Standaardwaarde font",
    "",
    "Largeur fixe standard",
    "",
    "tasavÃ¤linen kirjasintyyppi",
    "",
    "Fuente tamaño fijo defecto",
    "",
    "",
    "",
    "Alapértelmezett fixméretû betûtipus",
    "Font de mida fixa per defecte",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Default Small Font",
    "Std. kleine Schrift",
    "",
    "Car. piccolo pred.",
    "Standaard klein font",
    "",
    "Petite police standard",
    "",
    "pieni kirjasintyyppi",
    "",
    "Fuente pequeña defecto",
    "",
    "",
    "",
    "Alapértelmezett kisméretû betûtipus",
    "Font petite per defecte",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "General",
    "Allgemein",
    "",
    "Generale",
    "Algemeen",
    "",
    "Généralité",
    "",
    "Yleiset",
    "",
    "General",
    "",
    "",
    "",
    "Általános",
    "General",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Logos & Symbols",
    "Logos & Symbole",
    "",
    "Loghi e simboli",
    "Logo's & Symbolen",
    "",
    "Logos et symboles",
    "",
    "Logot ja symbolit",
    "",
    "Logos y símbolos",
    "",
    "",
    "",
    "Logók és szimbólumok",
    "Emblemes i simbols",
#if VDRVERSNUM >= 10302
    "»ÞÓÞâØßë & áØÜÒÞÛë",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Animated Text",
    "Bewegter Text",
    "",
    "Testo animato",
    "Geanimeerde tekst",
    "",
    "Texte défilant",
    "",
    "Tekstien elÃ¤vÃ¶inti",
    "",
    "Texto animado",
    "",
    "",
    "",
    "Animált szöveg",
    "Texte animad",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Fonts",
    "Fonts",
    "",
    "Caratteri",
    "Fonts",
    "",
    "Les polices",
    "",
    "Kirjasintyypit",
    "",
    "Fuentes",
    "",
    "",
    "",
    "Betûtipusok",
    "Fonts",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPGSearch",
    "EPGSearch",
    "",
    "EPGSearch",
    "EPGsearch",
    "",
    "Recherche EPG",
    "",
    "EPGSearch",
    "",
    "EPGSearch",
    "",
    "",
    "",
    "EPGSearch",
    "EPGSearch",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "elapsed",
    "abgelaufene",
    "",
    "trascorso",
    "gedane",
    "",
    "écoulé",
    "",
    "kulunut",
    "",
    "transcurrido",
    "",
    "",
    "",
    "eltelt",
    "transcorregut",
#if VDRVERSNUM >= 10302
    "ØáâÕÚèØÕ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "remaining",
    "restliche",
    "",
    "rimasto",
    "resterend",
    "",
    "restant",
    "",
    "jÃ¤ljellÃ¤ oleva",
    "",
    "restante",
    "",
    "",
    "",
    "hátralevõ",
    "falten",
#if VDRVERSNUM >= 10302
    "ÞáâÐÛìÝëÕ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "percent",
    "Prozent",
    "",
    "percentuale",
    "procent",
    "",
    "Pourcentage",
    "",
    "prosentti",
    "",
    "porcentaje",
    "",
    "",
    "",
    "hátralevõ",
    "per cent",
#if VDRVERSNUM >= 10302
    "ßàÞæÕÝâ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "elapsed/remaining",
    "abgelaufene/restliche",
    "",
    "trascorso/rimasto",
    "resterend",
    "",
    "restant",
    "",
    "jÃ¤ljellÃ¤ oleva",
    "",
    "transcurrido/restante",
    "",
    "",
    "",
    "eltelt/hátralevõ",
    "transcorregut/falten",
#if VDRVERSNUM >= 10302
    "ÞáâÐÛìÝëÕ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "never",
    "nie",
    "",
    "mai",
    "nooit",
    "",
    "jamais",
    "",
    "ei koskaan",
    "",
    "nunca",
    "",
    "",
    "",
    "soha",
    "mai",
#if VDRVERSNUM >= 10302
    "ÝØÚÞÓÔÐ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "use size.vdr only",
    "nur size.vdr verwenden",
    "",
    "usa solo size.vdr",
    "alleen size.vdr gebruiken",
    "",
    "utiliser seulement size.vdr",
    "",
    "vain jos size.vdr",
    "",
    "sólo usar size.vdr",
    "",
    "",
    "",
    "csak a .vdr méret használata",
    "fer servir només tamany vdr",
#if VDRVERSNUM >= 10302
    "ØáßÞÛì×ÞÒÐâì âÞÛìÚÞ size.vdr",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "always",
    "immer",
    "",
    "sempre",
    "Altijd",
    "",
    "toujours",
    "",
    "aina",
    "",
    "siempre",
    "",
    "",
    "",
    "mindig",
    "sempre",
#if VDRVERSNUM >= 10302
    "ÒáÕÓÔÐ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Last line",
    "Letzter Zeile",
    "",
    "Ultima riga",
    "Laatste lijn",
    "",
    "Dernière ligne",
    "",
    "alimmalla rivillÃ¤",
    "",
    "Última línea",
    "",
    "",
    "",
    "Utolsó sor",
    "Darrera línia",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Help buttons",
    "Hilfe Tasten",
    "",
    "Tasti aiuto",
    "Help knoppen",
    "",
    "Button aide",
    "",
    "vÃ¤rinÃ¤ppÃ¤inrivillÃ¤",
    "",
    "Botones de ayuda",
    "",
    "",
    "",
    "Help gombok",
    "Botons d'ajuda",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Free last line",
    "freie letzte Zeile",
    "",
    "Ultima riga libera",
    "Vrije laatste lijn",
    "",
    "Dernière ligne libre",
    "",
    "alimmalla vapaalla rivillÃ¤",
    "",
    "Última línea libre",
    "",
    "",
    "",
    "Utolsó üres sor",
    "Darrera línia lliure",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "if required",
    "wenn benötigt",
    "",
    "se richiesto",
    "",
    "",
    "",
    "",
    "tarvittaessa",
    "",
    "si es necesario",
    "",
    "",
    "",
    "ha szükséges",
    "si és necessari",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Try 8bpp single area",
    "Einen 8bpp Bereich versuchen",
    "",
    "Prova area singola a 8bpp",
    "Op 8bpp bereik testen",
    "",
    "Essayer une surface à 8bpp",
    "",
    "Suosi yhtÃ¤ 8bpp kuva-aluetta",
    "",
    "Probar un área de 8bpp",
    "",
    "",
    "",
    "",
    "Seleccioneu un àrea simple 8bpp",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Round corners",
    "Ecken abrunden",
    "",
    "Angoli arrotondati",
    "",
    "",
    "",
    "",
    "",
    "",
    "Esquinas redondeadas",
    "",
    "",
    "",
    "Sarkok kerekítése",
    "Cantons redons",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Full title width",
    "Volle Titelbreite",
    "",
    "Lunghezza titolo completo",
    "Volle titelbreedte",
    "",
    "Largeur totale pour le titre",
    "",
    "LevitÃ¤ otsikkopalkki",
    "",
    "Ancho completo para título",
    "",
    "",
    "",
    "Teljes címsor szélesség",
    "Títol d'amplada completa",
#if VDRVERSNUM >= 10302
    "¿ÞÛÝÐï èØàØÝÐ ×ÐÓÞÛÞÒÚÐ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show VPS",
    "VPS anzeigen",
    "",
    "Mostra VPS",
    "VPS tonen",
    "",
    "Afficher le VPS",
    "",
    "NÃ¤ytÃ¤ VPS-tieto",
    "",
    "Mostrar VPS",
    "",
    "",
    "",
    "VPS információ",
    "Mostra VPS",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì VPS",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Dynamic OSD size",
    "Dynamische OSD-Größe",
    "",
    "Dimensione OSD dinamica",
    "Dynamische OSD grootte",
    "",
    "Taille dynamique de OSD",
    "",
    "Mukauta kuvaruutunÃ¤ytÃ¶n kokoa",
    "",
    "Tamaño OSD dinámico",
    "",
    "",
    "",
    "Dinamikus OSD méret",
    "Mida OSD dinàmique",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Menu OSD",
    "Menü OSD",
    "",
    "Menu OSD",
    "",
    "",
    "",
    "",
    "",
    "",
    "Menú OSD",
    "",
    "",
    "",
    "Menü OSD",
    "Menú oSD",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show info area in main menu",
    "Infobereich im Hauptmenü",
    "",
    "Mostra area info nel menu",
    "Info in hoofdmenu",
    "",
    "Surface d'infos dans le menu principal",
    "",
    "NÃ¤ytÃ¤ infoalue pÃ¤Ã¤valikossa",
    "",
    "Mostrar info en menú principal",
    "",
    "",
    "",
    "Infó terület a fõmenüben",
    "Mostra l'àrea d'informació en el menú principal",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì ØÝä. ÞÑÛÐáìâ Ò ÓÛ. ÜÕÝî",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Min width of info area",
    "  Minimale Infobereich-Breite",
    "",
    "  Larghezza min. area info",
    "  Infobereik scrollen",
    "",
    "  Barre de défilement dans la surface info",
    "",
    "  Infoalueen minimileveys",
    "",
    "  Anchura mín. para la info",
    "",
    "",
    "",
    "  Infó terület min. szélessége",
    "Amplada mínima de l'àrea d'informació",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show messages in menu on",
    "Meldungen im Menü über",
    "",
    "Mostra messaggi nel menu",
    "Toon berichten in menu aan",
    "",
    "Afficher les messages dans le menu",
    "",
    "NÃ¤ytÃ¤ viestit valikossa",
    "",
    "Mostrar mensajes en el menú",
    "",
    "",
    "",
    "Üzenetek megjelenítése a menüben",
    "Mostra els missatges en el menú activat",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show scrollbar in menu",
    "Bildlaufleiste im Menü anzeigen",
    "",
    "Mostra barra scorrimento nel menu",
    "  Symbolen in menu tonen",
    "",
    "  dans le menu",
    "",
    "NÃ¤ytÃ¤ vierityspalkki valikossa",
    "",
    "Mostrar barra de scroll en menú",
    "",
    "",
    "",
    "Görgetõsáv a menüben",
    "Mostra barres de desplaçament en el menú",
#if VDRVERSNUM >= 10302
    "  ¿ÞÚÐ×Ðâì áØÜÒÞÛë Ò ÜÕÝî",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPG & Recording Details OSD",
    "EPG- & Aufnahmen-Details OSD",
    "",
    "OSD EPG e dettagli registrazioni",
    "",
    "",
    "",
    "",
    "",
    "",
    "EPG y detalles de grabación OSD",
    "",
    "",
    "",
    "EPG és felvétel részl. OSDje",
    "EPG y detalls de gravació OSD",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show auxiliary information",
    "Zusatzinfo anzeigen",
    "",
    "Mostra info ausiliare",
    "Toon hulp informatie",
    "",
    "Afficher informations auxiliaires",
    "",
    "NÃ¤ytÃ¤ lisÃ¤tiedot",
    "Pokazuj informacje pomocnicze",
    "Mostrar información adicional",
    "",
    "Visa extrainformation",
    "",
    "További információk",
    "Mostra la informació auxiliar",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì àÐáè. ØÝäÞàÜÐæØî",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Lisainfo näitamine",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show recording's size",
    "Aufnahmengröße anzeigen",
    "",
    "Mostra dimensione reg.",
    "Opnamegrootte tonen",
    "",
    "Afficher la taille des enregistrements",
    "",
    "NÃ¤ytÃ¤ tallenteen koko",
    "",
    "Mostrar tamaño de grabación",
    "",
    "",
    "",
    "Felvételméretek",
    "Mostra la mida de la gravació",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì àÐ×ÜÕàë ×ÐßØáÕÙ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Channel Info OSD",
    "Kanalinfo OSD",
    "",
    "OSD info canale",
    "",
    "",
    "",
    "",
    "",
    "",
    "Info canal OSD",
    "",
    "",
    "",
    "Csatorna infó OSDje",
    "Canal d'informació OSD",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show remaining/elapsed time",
    "Zeige abgel./restl. Zeit",
    "",
    "Mostra tempo rim./trasc.",
    "Toon resterend/gedane tijd",
    "",
    "Afficher le temps écoulé/restant",
    "",
    "NÃ¤ytÃ¤ tapahtuman aika",
    "",
    "Mostrar tiempo restante/transcurrido",
    "",
    "",
    "",
    "Eltelt/hátralevõ idõ",
    "Mostra el temps restant/transcorregut",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì ÞáâÐÒ./ßàÞèÕÔ. ÒàÕÜï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Width of progress bar",
    "Breite der Fortschrittsanzeige",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Anchura para barra de progreso",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show signal info",
    "Zeige Signal-Informationen",
    "",
    "Mostra info segnale",
    "  Mail-ikoon tonen",
    "",
    "  Afficher l'icône courriel",
    "",
    "  NÃ¤ytÃ¤ sÃ¤hkÃ¶postikuvake",
    "",
    "Mostrar info de señal",
    "",
    "",
    "",
    "Jelszint",
    "Mostra la senyal d'informació",
#if VDRVERSNUM >= 10302
    "  ¿ÞÚÐ×Ðâì ×ÝÐçÞÚ íÛÕÚâ. ßÞçâë",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Width of signal info",
    "  Breite der Signal-Informationen",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "  Anchura para info de señal",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show CA system as text",
    "CA System als Text anzeigen",
    "",
    "Mostra sistema CA come testo",
    "",
    "",
    "",
    "",
    "",
    "",
    "Mostrar sistema CA como texto",
    "",
    "",
    "",
    "Kódolási rendszer szövegként",
    "Mostra el sistema CA com a text",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show Category - Genre / Contents",
    "Kategory - Gengre / Inhalt anzeigen",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Mostrar Categoría - Género / Contenido",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "pixel algo",
    "Pixel-Algorithmus",
    "",
    "algoritmo pixel",
    "pixelalgoritme",
    "",
    "Algorithme pixel",
    "",
    "nÃ¤ytteistys",
    "",
    "Algoritmo píxel",
    "",
    "",
    "",
    "pixel algo",
    "pixel algo",
#if VDRVERSNUM >= 10302
    "ÐÛÓÞàØâÜ ßØÚáÕÛï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "ratio algo",
    "Ratio-Algorithmus",
    "",
    "algoritmo medio",
    "algoritmeratio",
    "",
    "Algorithme ratio",
    "",
    "skaalaus",
    "",
    "Algoritmo ratio",
    "",
    "",
    "",
    "méretarány algo",
    "raó algo",
#if VDRVERSNUM >= 10302
    "ÐÛÓÞàØâÜ áÞÞâÝÞèÕÝØï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "zoom image",
    "Zoomen",
    "",
    "ingrandisci immagine",
    "zoomen",
    "",
    "Agrandir image",
    "",
    "zoomaus",
    "",
    "Aumentar imagen",
    "",
    "",
    "",
    "kép nagyítása",
    "zoom de la imatge",
#if VDRVERSNUM >= 10302
    "ÃÒÕÛØçØâì",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "only if new mail present",
    "nur bei neuer Mail",
    "",
    "solo se presenti nuove email",
    "alleen bij nieuwe mail",
    "",
    "juste lors d'un courriel",
    "",
    "jos uutta postia",
    "",
    "sólo si hay nuevo correo",
    "",
    "",
    "",
    "csak ha új levél érkezett",
    "només si hi ha nou correu",
#if VDRVERSNUM >= 10302
    "âÞÛìÚÞ ßàØ ÝÞÒÞÜ áÞÞÑéÕÝØØ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "active only",
    "nur aktive",
    "",
    "solo attivo",
    "",
    "",
    "",
    "",
    "",
    "",
    "sólo activo",
    "",
    "",
    "",
    "csak ha aktív",
    "només actiu",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Flushing channel logo cache...",
    "Logo-Cache wird geleert...",
    "",
    "Pulizia cache loghi canali...",
    "Kanaallogo cache legen...",
    "",
    "Suppression du cache...",
    "",
    "TyhjennetÃ¤Ã¤n vÃ¤limuistia...",
    "Opró¿niam cache logo kana³u...",
    "Limpiando la caché...",
    "",
    "Tömmer cachen...",
    "",
    "Csatornalogó tár ürítése...",
    "Flushing channel logo cache...",
#if VDRVERSNUM >= 10302
    "¾çØéÐî ÚÕè...",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Kanalilogo vahemälu tühjendamine...",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show symbols",
    "Symbole anzeigen",
    "",
    "Mostra simboli",
    "Symbolen tonen",
    "",
    "Afficher symbole",
    "",
    "NÃ¤ytÃ¤ symbolit",
    "Pokazuj symbole",
    "Mostrar símbolos",
    "",
    "Visa symboler",
    "",
    "Szimbóiumok",
    "Mostra els símbols",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì áØÜÒÞÛë",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Sümbolite näitamine",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show symbols in menu",
    "  Symbole im Menü",
    "",
    "  Mostra simboli menu",
    "  Symbolen in menu tonen",
    "",
    "  dans le menu",
    "",
    "  NÃ¤ytÃ¤ symbolit valikossa",
    "",
    "  Mostrar símbolos en menú",
    "",
    "",
    "",
    "  Szimbóiumok a menüben",
    "  Mostra els símbols en el menú",
#if VDRVERSNUM >= 10302
    "  ¿ÞÚÐ×Ðâì áØÜÒÞÛë Ò ÜÕÝî",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show symbols in replay",
    "  Symbole bei der Wiedergabe",
    "",
    "  Mostra simboli esecuzione",
    "  Symbolen bij weergave tonen",
    "",
    "  dans lecture",
    "",
    "  NÃ¤ytÃ¤ symbolit toistettaessa",
    "",
    "  Mostrar símbolos en reproducción",
    "",
    "",
    "",
    "  Szimbóiumok visszajátszáskor",
    "  Mostra els símbols en la reproducció",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show symbols in messages",
    "  Symbole bei den Meldungen",
    "",
    "  Mostra simboli messaggi",
    "  Symbolen bij berichten tonen",
    "",
    "  dans les messages",
    "",
    "  NÃ¤ytÃ¤ symbolit viesteissÃ¤",
    "",
    "  Mostrar símbolos en mensajes",
    "",
    "",
    "",
    "  Szimbóiumok üzenetekben",
    "  Mostra els símbols en els missatges",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show symbols in audio",
    "  Symbole bei Audio",
    "",
    "  Mostra simboli audio",
    "  Symbolen bij audio tonen",
    "",
    "  dans audio",
    "",
    "  NÃ¤ytÃ¤ symbolit Ã¤Ã¤nivalikossa",
    "",
    "  Mostrar símbolos en audio",
    "",
    "",
    "",
    "  Szimbóiumok hangsávokban",
    "  Mostra els símbols a en el so",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Colored status symbols in EPG details",
    "Farbige Statussymbole in den EPG-Details",
    "",
    "Simboli di stato colorati nei dettagli EPG",
    "",
    "",
    "",
    "",
    "",
    "",
    "Símbolos de estado coloreados en la EPG",
    "",
    "",
    "",
    "EPG-ben színes állapotszimbólumok",
    "Símbols d'estat en color en els detalls EPG",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show symbols in lists",
    "Symbole in Listen",
    "",
    "Mostra simboli elenchi",
    "Symbolen in lijsten tonen",
    "",
    "Symboles dans les listes",
    "",
    "NÃ¤ytÃ¤ tapahtumien symbolit",
    "",
    "Mostrar símbolos en listas",
    "",
    "",
    "",
    "Szimbóiumok listákban",
    "Mostra símbols a les llistes",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì áØÜÒÞÛë Ò áßØáÚÐå",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show progressbar in lists",
    "Fortschrittbalken in Listen anzeigen",
    "",
    "Mostra indicatore elenchi",
    "",
    "",
    "",
    "",
    "",
    "",
    "Mostrar barra de progreso en listas",
    "",
    "",
    "",
    "Állapotjelzõ a listákban",
    "Mostra la barra de progrés a les llistes",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show marker in lists",
    "Symbol vor Listeneinträgen",
    "",
    "Mostra marcatore elenchi",
    "Markering in lijsten tonen",
    "",
    "Marque devant les listes",
    "",
    "NÃ¤ytÃ¤ valintasymboli",
    "",
    "Mostrar marcador en listas",
    "",
    "",
    "",
    "Vágási pontok listákban",
    "Mostra les marques a les llistes",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì ÜÕâÚã Ò áßØáÚÐå",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show status symbols",
    "Statussymbole anzeigen",
    "",
    "Mostra simboli stato",
    "Status symbolen tonen",
    "",
    "Afficher symbole de status",
    "",
    "NÃ¤ytÃ¤ symbolit",
    "Pokazuj symbole",
    "Mostrar símbolos de estado",
    "",
    "Visa symboler",
    "",
    "Állapotszimbólumok",
    "Mostra els símbols d'estat",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì áØÜÒÞÛë",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Sümbolite näitamine",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show flags",
    "  Fahnen anzeigen",
    "",
    "  Mostra bandierine",
    "  Vlaggen tonen",
    "",
    "  Afficher drapeau",
    "",
    "  NÃ¤ytÃ¤ liput",
    "",
    "  Mostrar banderas",
    "",
    "",
    "",
    "  Zászlók",
    "  Mostra les marques",
#if VDRVERSNUM >= 10302
    "  ¿ÞÚÐ×Ðâì äÛÐÓØ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show WSS mode symbols",
    "  Symbol für WSS Modus",
    "",
    "  Mostra simboli mod. WSS",
    "WSS modus symbolen tonen",
    "",
    " Afficher mode symboles WSS",
    "",
    "  NÃ¤ytÃ¤ WSS-symbolit",
    "",
    "  Mostrar símbolos modo WSS",
    "",
    "",
    "",
    "  WSS mód",
    "  Mostra el mode de símbols WSS",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show mail icon",
    "  Zeige Mail-Icon",
    "",
    "  Mostra icona email",
    "  Mail-ikoon tonen",
    "",
    "  Afficher l'icône courriel",
    "",
    "  NÃ¤ytÃ¤ sÃ¤hkÃ¶postikuvake",
    "",
    "  Mostrar icono de correo",
    "",
    "",
    "",
    "  Új levél ikon",
    "  Mostra els icones de correu",
#if VDRVERSNUM >= 10302
    "  ¿ÞÚÐ×Ðâì ×ÝÐçÞÚ íÛÕÚâ. ßÞçâë",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show event/recording images",
    "Bilder in EPG/Aufnahmendetails",
    "",
    "Mostra immagini evento/reg.",
    "Voorstelling/opname figuren tonen",
    "",
    "Images dans les EPG et détails d'enregistrements",
    "",
    "NÃ¤ytÃ¤ kuvat lisÃ¤tietovalikossa",
    "",
    "Mostrar imágenes grabación/suceso",
    "",
    "",
    "",
    "Esemény/felvétel képek",
    "Mostra les imatges d'esdeveniments/registre",
#if VDRVERSNUM >= 10302
    "¸×ÞÑàÐÖÕÝØï Ò EPG",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Resize images",
    "  Bildberechnung benutzt",
    "",
    "  Ridimensiona immagini",
    "  Aanpassen beeldgrootte",
    "",
    "  Redimensionne les images",
    "",
    "  Muokkaa kuvien kokoa",
    "",
    "  Redimensionar imágenes",
    "",
    "",
    "",
    "  Képek átméretezése",
    "  Redimensiona imatges",
#if VDRVERSNUM >= 10302
    "  ¿ÕàÕàÕèÐâì ØáßÞÛì×ãï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Image width",
    "  Bildbreite",
    "",
    "  Larghezza immagine",
    "  Beeldbreedte",
    "",
    "  Largeur",
    "",
    "  Kuvien leveys",
    "",
    "  Anchura de imagen",
    "",
    "",
    "",
    "  Kép szélessége",
    "  Amplada de la imatge",
#if VDRVERSNUM >= 10302
    "  ÈØàØÝÐ Ø×ÞÑàÐÖÕÝØï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Image height",
    "  Bildhöhe",
    "",
    "  Altezza immagine",
    "  Beeldhoogte",
    "",
    "  Hauteur",
    "",
    "  Kuvien korkeus",
    "",
    "  Altura de imagen",
    "",
    "",
    "",
    "  Kép magassága",
    "  Alçada de la imatge",
#if VDRVERSNUM >= 10302
    "  ²ëáÞâÐ Ø×ÞÑàÐÖÕÝØï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Image format",
    "  Bildformat",
    "",
    "  Formato immagine",
    "  Beeldformaat",
    "",
    "  Format d'image",
    "",
    "  Kuvaformaatti",
    "",
    "  Formato de imagen",
    "",
    "",
    "",
    "  Kép formátuma",
    "  Format de la imatge",
#if VDRVERSNUM >= 10302
    "  ÄÞàÜÐâ Ø×ÞÑàÐÖÕÝØï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show channel logos",
    "Kanal-Logos anzeigen",
    "",
    "Mostra loghi canali",
    "Toon kanaallogo's",
    "",
    "Afficher logos des chaînes",
    "",
    "NÃ¤ytÃ¤ kanavalogot",
    "Pokazuj logo kana³u",
    "Mostrar logos de los canales",
    "",
    "Visa kanallogotyper",
    "",
    "Csatornalogók",
    "Mostra els logos del canal",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì ÛÞÓÞ ÚÐÝÐÛÞÒ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Kanalilogo näitamine",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Identify channel by",
    "  Kanal-Identifikation durch",
    "",
    "  Identifica canale per",
    "  Identificeer kanaal door",
    "",
    "  Identifier chaîne par",
    "",
    "  Tunnista kanava",
    "  Rozpoznaj kana³ po",
    "  Identificar el canal por",
    "",
    "  Identifiera kanal med",
    "",
    "  Csatornák azonosítása",
    "  Identifica el canal per",
#if VDRVERSNUM >= 10302
    "  ¾ßàÕÔÕÛïâì ÚÐÝÐÛ ßÞ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "  Kanali tuvastamise meetod",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "name",
    "Name",
    "",
    "nome",
    "naam",
    "",
    "Nom",
    "",
    "nimestÃ¤",
    "nazwa",
    "nombre",
    "",
    "namn",
    "",
    "név szerint",
    "nom",
#if VDRVERSNUM >= 10302
    "ÝÐ×ÒÐÝØî",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "nimi",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "data",
    "ID",
    "",
    "dati",
    "data",
    "",
    "Donnée",
    "",
    "tiedoista",
    "parametry",
    "datos",
    "",
    "data",
    "",
    "adat szerint",
    "data",
#if VDRVERSNUM >= 10302
    "ÔÐÝÝëÜ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "andmed",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Channel logo cache size",
    "Größe des Logo-Caches",
    "",
    "Dim. cache loghi canali",
    "Kanaallogo cache",
    "",
    "Taille du cache des logos",
    "",
    "VÃ¤limuistin koko kanavalogoille",
    "Rozmiar cache dla logo kana³u",
    "Tamaño de caché para los logos",
    "",
    "Cachestorlek för logotyper",
    "",
    "Csatonalogó gyorsítótár mérete",
    "MIda provisional del logo del canal",
#if VDRVERSNUM >= 10302
    "ÀÐ×ÜÕà ÚÕèÐ ÛÞÓoâØßÞÒ ÚÐÝÐÛÞÒ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Kanalilogo vahemälu suurus",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Button$Flush cache",
    "Cache leeren",
    "",
    "Svuota cache",
    "Cache legen",
    "",
    "Supprimer cache",
    "",
    "TyhjennÃ¤",
    "Opró¿nij cache",
    "Limpiar caché",
    "",
    "Töm cachen",
    "",
    "gyorsítótár",
    "Botons$Flush cache",
#if VDRVERSNUM >= 10302
    "¾çØáâØâì ÚÕè",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Tühjenda",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "left and right",
    "links und rechts",
    "",
    "sinistra e destra",
    "links en rechts",
    "",
    "gauche et droite",
    "",
    "edestakaisin",
    "",
    "izquierda y derecha",
    "",
    "",
    "",
    "balra-jobbra",
    "esquerra i dreta",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "to the left",
    "nach links",
    "",
    "verso sinistra",
    "naar links",
    "",
    "vers la gauche",
    "",
    "vasemmalle",
    "",
    "a la izquierda",
    "",
    "",
    "",
    "balra",
    "a l'esquerra",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Enable",
    "Verwenden",
    "",
    "Abilita",
    "Toelaten",
    "",
    "Permettre",
    "",
    "KÃ¤ytÃ¤ elÃ¤vÃ¶intiÃ¤",
    "",
    "Activar",
    "",
    "",
    "",
    "Engedélyezve",
    "Activat",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scroll OSD title",
    "  OSD Titel scrollen",
    "",
    "  Scorri titolo OSD",
    "  OSD titel scrollen",
    "",
    "  Défilement dans le titre du OSD",
    "",
    "  VieritÃ¤ valikon otsikkoa",
    "",
    "  Título OSD del scroll",
    "",
    "",
    "",
    "  OSD címsor görgetése",
    "  Mou el títol OSD",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scroll info area",
    "  Infobereich scrollen",
    "",
    "  Scorri info area",
    "  Infobereik scrollen",
    "",
    "  Barre de défilement dans la surface info",
    "",
    "  VieritÃ¤ infoaluetta",
    "",
    "  Scroll para el área info",
    "",
    "",
    "",
    "  Infó mezõ görgetése",
    "  Mou l'àrea d'informació",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scroll active list items",
    "  Aktive Listenzeile scrollen",
    "",
    "  Scorri elenco valori attivi",
    "  Lijst aktieve punten scrollen",
    "",
    "  Barre de défilement dans la liste active",
    "",
    "  VieritÃ¤ aktiivista valintaa",
    "",
    "  Scroll para la lista activa",
    "",
    "",
    "",
    "  Aktív listaelemek görgetése",
    "  Mou la llista d'ítems actius",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scroll other items",
    "  Andere Bereiche scrollen",
    "",
    "  Scorri altri valori",
    "  Andere punten scrollen",
    "",
    "  Barre de défilement dans d'autres parties",
    "",
    "  VieritÃ¤ muita alueita",
    "",
    "  Scroll para otros datos",
    "",
    "",
    "",
    "  Egyéb elemek görgetése",
    "  Mou altres ítems",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scroll behaviour",
    "  Scroll-Verhalten",
    "",
    "  ModalitÃ  scorrimento",
    "  Scroll gedrag",
    "",
    "  Comportement de défilement",
    "",
    "  Vieritystapa",
    "",
    "  Comportamiento del scroll",
    "",
    "",
    "",
    "  Görgetés viselkedése",
    "  Mou els comportaments",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scroll delay (ms)",
    "  Scroll-Verzögerung (ms)",
    "",
    "  Ritardo scorrimento (ms)",
    "  Scrollvertraging (ms)",
    "",
    "  Délai de défilement (ms)",
    "",
    "  Vierityksen viive (ms)",
    "",
    "  Retardo del scroll (ms)",
    "",
    "",
    "",
    "  Görgetés késleltetése (ms)",
    " Mou el retard (ms)",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scroll pause (ms)",
    "  Scroll-Pause (ms)",
    "",
    "  Pausa scorrimento (ms)",
    "  Scrollpause (ms)",
    "",
    "  Pause de défilement (ms)",
    "",
    "  Vierityksen tauko (ms)",
    "",
    "  Pausa del scroll (ms)",
    "",
    "",
    "",
    "  Görgetés leállítása (ms)",
    "  Mou la pausa (ms)",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Blink pause (ms)",
    "  Blink-Pause (ms)",
    "",
    "  Pausa lampeggiante (ms)",
    "  Blinkpauze (ms)",
    "",
    "  Pause de clignotement (ms)",
    "",
    "  Vilkutuksen tauko (ms)",
    "",
    "  Pausa del parpadeo (ms)",
    "",
    "",
    "",
    "  Villogás leállítása (ms)",
    "  Pausa \"Blink\" (ms)",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Name",
    "Name",
    "",
    "Nome",
    "Naam",
    "",
    "Nom",
    "",
    "Nimi",
    "",
    "Nombre",
    "",
    "",
    "",
    "Név",
    "Nom",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Size",
    "Größe",
    "",
    "Dimensione",
    "Grootte",
    "",
    "Taille",
    "",
    "Koko",
    "",
    "Tamaño",
    "",
    "",
    "",
    "Méret",
    "Tamany",
#if VDRVERSNUM >= 10302
    "ÀÐ×ÜÕà",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Width",
    "Weite",
    "",
    "Larghezza",
    "Breedte",
    "",
    "Largeur",
    "",
    "Leveys",
    "",
    "Anchura",
    "",
    "",
    "",
    "Szélesség",
    "Amplada",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "No TrueType fonts installed!",
    "Keine TrueType Schriften installiert!",
    "",
    "Nessun car. TrueType installato!",
    "Geen TrueType fonten geinstalleerd!",
    "",
    "Il n'y a pas de police TrueType d'installé!",
    "",
    "TrueType-kirjasintyyppejÃ¤ ei lÃ¶ydy!",
    "",
    "¡Ninguna fuente TrueType instalada!",
    "",
    "",
    "",
    "Nincs TrueType betûkészlet telepítve!",
    "No hi ha fonts TrueType instal·lades",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "No TTF support!",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "¡Sin soporte TTF!",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Fixed Font",
    "Schrift mit fester Breite",
    "",
    "Carattere fisso",
    "Vaste waarde font",
    "",
    "Police avec une largeur fixe",
    "",
    "TasavÃ¤linen kirjasintyyppi",
    "",
    "Fuente Fija",
    "",
    "",
    "",
    "Fixméretû betûkészlet",
    "Font de mida fitxe",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Button$Set",
    "Ändern",
    "",
    "Imposta",
    "Veranderen",
    "",
    "Changer",
    "",
    "Aseta",
    "",
    "Cambiar",
    "",
    "",
    "",
    "Beállítás",
    "Button$Set",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "OSD title",
    "OSD Titel",
    "",
    "Titolo OSD",
    "OSD titel",
    "",
    "Titre OSD",
    "",
    "Valikon otsikko",
    "",
    "Título OSD",
    "",
    "",
    "",
    "OSD címsor",
    "Títol OSD",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Messages",
    "Meldungen",
    "",
    "Messaggi",
    "Meldingen",
    "",
    "Message",
    "",
    "Viestit",
    "",
    "Mensajes",
    "",
    "",
    "",
    "Üzenetek",
    "MIssatges",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Date",
    "Datum",
    "",
    "Data",
    "Datum",
    "",
    "Date",
    "",
    "PÃ¤ivÃ¤ys",
    "",
    "Fecha",
    "",
    "",
    "",
    "Dátum",
    "Data",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Help keys",
    "Farb-Tasten",
    "",
    "Tasti aiuto",
    "Help toetsen",
    "",
    "Touche couleur",
    "",
    "VÃ¤rinÃ¤ppÃ¤imet",
    "",
    "Botones de ayuda",
    "",
    "",
    "",
    "Help gombok",
    "Tecles d'ajuda",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Channelinfo: title",
    "Kanalinfo: Titel",
    "",
    "Info canale: titolo",
    "Kanaalinfo: titel",
    "",
    "Chaîne info: titre ",
    "",
    "Kanavatieto: ohjelman nimi",
    "",
    "Info canal: título",
    "",
    "",
    "",
    "Csatornainfó: cím",
    "Canal d'informació: títol",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Channelinfo: subtitle",
    "Kanalinfo: Untertitel",
    "",
    "Info canale: sottotitoli",
    "Kanaalinfo: ondertitel",
    "",
    "Chaîne info: sous-titres",
    "",
    "Kanavatieto: ohjelman kuvaus",
    "",
    "Info canal: subtítulo",
    "",
    "",
    "",
    "Csatornainfó: alcím",
    "Canal d'informació: sub-títol",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Channelinfo: language",
    "Kanalinfo: Sprache",
    "",
    "Info canale: lingua",
    "Kanaalinfo: taal",
    "",
    "Chaîne info: langue",
    "",
    "Kanavatieto: kieli",
    "",
    "Info canal: idioma",
    "",
    "",
    "",
    "Csatornainfó: nyelv",
    "Canal d'informació: idioma",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "List items",
    "Listen",
    "",
    "Elenco valori",
    "Lijsten",
    "",
    "Liste",
    "",
    "Listat",
    "",
    "Listado",
    "",
    "",
    "",
    "Lista elemek",
    "Llista d'ítems",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Info area: timers title",
    "Infobereich: Timer Titel",
    "",
    "Info area: titoli timer",
    "Infobereik: Timertitel",
    "",
    "Barre d'information: Titre Progammation",
    "",
    "Infoalue: ajastimen otsikko",
    "",
    "Área info: título programación",
    "",
    "",
    "",
    "Infó terület: idõzítõk címe",
    "Àrea d'informació: títols de temporitzadors",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Info area: timers text",
    "Infobereich: Timer Text",
    "",
    "Info area: testo timer",
    "Infobereik: Timertekst",
    "",
    "Barre d'information: Text programmation",
    "",
    "Infoalue: ajastimen leipÃ¤teksti",
    "",
    "Área info: texto programación",
    "",
    "",
    "",
    "Infó terület: idõzítõk leírása",
    "Àrea d'informació: text de temporitzadors",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Info area: warning title",
    "Infobereich: Warnung Titel",
    "",
    "Info area: titolo avviso",
    "Infobereik: waarschuwing titel",
    "",
    "Barre d'information: avertissement titre",
    "",
    "Infoalue: varoituksen otsikko",
    "",
    "Área info: título aviso",
    "",
    "",
    "",
    "Infó terület: figyelmeztetés címe",
    "Àrea d'informació: títol d'avís",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Info area: warning text",
    "Infobereich: Warnung Text",
    "",
    "Info area: testo avviso",
    "Infobereik: waarschuwing tekst",
    "",
    "Barre d'information: texte d'avertissement",
    "",
    "Infoalue: varoituksen leipÃ¤teksti",
    "",
    "Área info: texto aviso",
    "",
    "",
    "",
    "Infó terület: figyelmeztetés leírása",
    "Àrea d'informació: text d'avís",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Details: title",
    "Details: Titel",
    "",
    "Dettagli: titolo",
    "Details: titel",
    "",
    "Détails: Titre",
    "",
    "LisÃ¤tiedot: ohjelman nimi",
    "",
    "Detalles: título",
    "",
    "",
    "",
    "Részletek: cím",
    "Detalls: títol",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Details: subtitle",
    "Details: Untertitel",
    "",
    "Dettagli: sottotitoli",
    "Details: ondertitel",
    "",
    "Détails: Sous-titre",
    "",
    "LisÃ¤tiedot: ohjelman kuvaus",
    "",
    "Detalles: subtítulo",
    "",
    "",
    "",
    "Részletek: alcím",
    "Detalls: sub-titol",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Details: date",
    "Details: Datumszeile",
    "",
    "Dettagli: data",
    "Details: datum",
    "",
    "Détails: date",
    "",
    "LisÃ¤tiedot: pÃ¤ivÃ¤mÃ¤Ã¤rÃ¤",
    "",
    "Detalles: fecha",
    "",
    "",
    "",
    "Részletek: dátum",
    "Detalls: data",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Details: text",
    "Details: Text",
    "",
    "Dettagli: testo",
    "Details: tekst",
    "",
    "Détails: Texte",
    "",
    "LisÃ¤tiedot: leipÃ¤teksti",
    "",
    "Detalles: texto",
    "",
    "",
    "",
    "Részletek: leírás",
    "Detalls: texte",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Replay: times",
    "Wiedergabe: Zeiten",
    "",
    "Riproduzione: volte",
    "Weergave: tijden",
    "",
    "Rejouer : périodes",
    "",
    "Toisto: kellonajat",
    "",
    "Reproducir: veces",
    "",
    "",
    "",
    "Visszajátszás: idõpontok",
    "Reproducció: temps",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "if exists",
    "wenn vorhanden",
    "",
    "se esiste",
    "wanneer aanwezig",
    "",
    "si existant",
    "",
    "jos olemassa",
    "",
    "si existe",
    "",
    "",
    "",
    "ha létezik",
    "si existeix",
#if VDRVERSNUM >= 10302
    "ÕáÛØ Ò ÝÐÛØçØØ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Number of Reruns",
    "Anzahl Wiederholungen",
    "",
    "Numero repliche",
    "aantal herhalingen",
    "",
    "Nombre de répétitions",
    "",
    "Uusintojen lukumÃ¤Ã¤rÃ¤",
    "",
    "Número de repeticiones",
    "",
    "",
    "",
    "Ismétlések száma",
    "Nombre de repeticions",
#if VDRVERSNUM >= 10302
    "ºÞÛØçÕáâÒÞ ßÞÒâÞàÕÝØÙ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Use Subtitle for reruns",
    "Verw. Untertitel für Wdh.",
    "",
    "Utilizza sottotitoli repliche",
    "Gebr. ondertitlel voor herh.",
    "",
    "Utilise sous-titres pour les répétitions",
    "",
    "KÃ¤ytÃ¤ lyhyttÃ¤ kuvausta uusinnoille",
    "",
    "Usar subtítulo para repeticiones",
    "",
    "",
    "",
    "Alcímek használata ismétlésekhez",
    "Fer servir sub-títols per les repeticions ",
#if VDRVERSNUM >= 10302
    "¸áßÞÛì×. ßÞÔ×ÐÓÞÛÞÒÚØ ÔÛï ßÞÒâÞàÕÝØï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show timer conflicts",
    "Timerkonflikte anzeigen",
    "",
    "Mostra conflitti timer",
    "Timerconflict tonen",
    "",
    "Afficher les conflits de programmation",
    "",
    "NÃ¤ytÃ¤ pÃ¤Ã¤llekkÃ¤iset ajastimet",
    "",
    "Mostrar conflictos de programación",
    "",
    "",
    "",
    "Idõzítõk ütközésének kijelzése",
    "Mostra els conflictes de temps",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×Ðâì ÚÞÝäÛØÚâë âÐÙÜÕàÞÒ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EnigmaNG skin",
    "EnigmaNG Oberfläche",
    "",
    "Stile interfaccia EnigmaNG",
    "EnigmaNG skin",
    "",
    "Skin EnigmaNG",
    "",
    "EnigmaNG-ulkoasu",
    "Skin EnigmaNG",
    "Piel EnigmaNG",
    "",
    "EnigmaNG-temat",
    "",
    "EnigmaNG bõr",
    "EnigmaNG skin",
#if VDRVERSNUM >= 10302
    "EnigmaNG áÚØÝ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "EnigmaNG kest",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Free-To-Air",
    "Free-To-Air",
    "",
    "in chiaro",
    "",
    "",
    "",
    "",
    "",
    "",
    "sin encriptar",
    "",
    "",
    "",
    "kódolatlan",
    "Free-To-Air",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "encrypted",
    "verschlüsselt",
    "",
    "codificato",
    "",
    "",
    "",
    "",
    "salattu",
    "",
    "encriptado",
    "",
    "",
    "",
    "kódolt",
    "encritat",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "*** Invalid Channel ***",
    "*** Ungültiger Kanal ***",
    "",
    "*** Canale NON valido ***",
    "*** Ongeldig Kanaal ***",
    "",
    "*** Chaîne non valable ***",
    "",
    "*** Virheellinen kanava ***",
    "",
    "*** Canal no válido ***",
    "",
    "",
    "",
    "*** Érvénytelen csatorna  ***",
    "*** Canal no vàlid ***",
#if VDRVERSNUM >= 10302
    "*** ½ÕßàÐÒØÛìÝëÙ ÚÐÝÐÛ ***",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "WARNING",
    "WARNUNG",
    "",
    "ATTENZIONE",
    "WAARSCHUWING",
    "",
    "ATTENTION",
    "",
    "VAROITUS",
    "",
    "AVISO",
    "",
    "",
    "",
    "FIGYELEM",
    "PERILL",
#if VDRVERSNUM >= 10302
    "¿Àµ´Ã¿Àµ¶´µ½¸µ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Timer conflict",
    "Timerkonflikt",
    "",
    "Conflitto timer",
    "Timerconflict",
    "",
    "Conflit de programmation",
    "",
    "PÃ¤Ã¤llekkÃ¤inen ajastin",
    "",
    "Conflicto de programación",
    "",
    "",
    "",
    "Idõzitõ átfedés",
    "Conflicte d'hora",
#if VDRVERSNUM >= 10302
    "ºÞÝäÛØÚâ âÐÙÜÕàÐ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Timer conflicts",
    "Timerkonflikte",
    "",
    "Conflitti timer",
    "Timerconflicten",
    "",
    "Conflits de programmation",
    "",
    "PÃ¤Ã¤llekkÃ¤isiÃ¤ ajastimia",
    "",
    "Conflictos de programación",
    "",
    "",
    "",
    "Idõzítõ átfedések",
    "Conflictes d'hores",
#if VDRVERSNUM >= 10302
    "ºÞÝäÛØÚâë âÐÙÜÕàÞÒ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "TIMERS",
    "TIMER",
    "",
    "TIMER",
    "TIMER",
    "",
    "PROGRAMMATION",
    "",
    "AJASTIMET",
    "",
    "PROGRAMACIONES",
    "",
    "",
    "",
    "IDÕZÍTÕK",
    "HORES",
#if VDRVERSNUM >= 10302
    "Â°¹¼µÀË",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "min",
    "min",
    "",
    "min",
    "min",
    "",
    "min",
    "",
    "min",
    "min",
    "min",
    "",
    "min",
    "",
    "min",
    "mínim",
#if VDRVERSNUM >= 10302
    "ÜØÝ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "min",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Content: ",
    "Inhalt: ",
    "",
    "Contenuto: ",
    "",
    "",
    "",
    "",
    "",
    "",
    "Contenido: ",
    "",
    "",
    "",
    "Tartalom:",
    "Contingut:",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Video",
    "Video",
    "",
    "Video",
    "",
    "",
    "",
    "",
    "",
    "",
    "Vídeo",
    "",
    "",
    "",
    "Videó",
    "Vídeo",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Audio",
    "Audio",
    "",
    "Audio",
    "",
    "",
    "",
    "",
    "",
    "",
    "Audio",
    "",
    "",
    "",
    "Hang",
    "Audio",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Subtitles",
    "Untertitel",
    "",
    "Sottotitoli",
    "",
    "",
    "",
    "",
    "Tekstitys",
    "",
    "Subtítulos",
    "",
    "",
    "",
    "Feliratok",
    "Subtitols",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "RERUNS OF THIS SHOW",
    "WIEDERHOLUNGEN",
    "",
    "REPLICHE DI QUESTO SPETTACOLO",
    "HERHALINGEN",
    "",
    "REPETITION",
    "",
    "TOISTUVAT TAPAHTUMAT",
    "",
    "REPETICIONES",
    "",
    "",
    "",
    "ISMÉTLÉSEK",
    "REPETICIONS D'AQUEST ESPECTACLE",
#if VDRVERSNUM >= 10302
    "¿¾²Â¾Àµ½¸Ï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "cut",
    "geschnitten",
    "",
    "taglia",
    "",
    "",
    "",
    "",
    "",
    "",
    "editado",
    "",
    "",
    "",
    "vágás",
    "talla",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Length",
    "Länge",
    "",
    "Durata",
    "",
    "",
    "",
    "",
    "",
    "",
    "Duración",
    "",
    "",
    "",
    "Hossz",
    "Longitud",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Format",
    "Format",
    "",
    "Formato",
    "",
    "",
    "",
    "",
    "",
    "",
    "Formato",
    "",
    "",
    "",
    "Formátum",
    "Format",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Est. bitrate",
    "Geschätzte Bitrate",
    "",
    "Bitrate estimato",
    "",
    "",
    "",
    "",
    "",
    "",
    "Bitrate est.",
    "",
    "",
    "",
    "Becsült bitr.",
    "Estat de la tasa de bits",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Auxiliary information",
    "Zusatzinformation",
    "",
    "Informazione ausiliare",
    "Hulp informatie",
    "",
    "Information auxiliare",
    "",
    "LisÃ¤tiedot",
    "Informacje pomocnicze",
    "Información adicional",
    "",
    "Extrainformation",
    "",
    "További információk",
    "Informació auxiliar",
#if VDRVERSNUM >= 10302
    "ÀÐáè. ØÝäÞàÜÐæØï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Lisainfo",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Mute",
    "Stumm",
    "",
    "Muto",
    "Geluid uit",
    "Muet",
    "Silence",
    "",
    "Mykistetty",
    "",
    "Silenciar",
    "",
    "",
    "",
    "Némítás",
    "Silenci",
#if VDRVERSNUM >= 10302
    "²ëÚÛ.×ÒãÚ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Volume",
    "Lautstärke",
    "",
    "Volume",
    "Volume",
    "",
    "Volume",
    "",
    "Ã„Ã¤nenvoimakkuus",
    "",
    "Volumen",
    "",
    "",
    "",
    "Hangerõ",
    "Volumen",
#if VDRVERSNUM >= 10302
    "³àÞÜÚÞáâì",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EnigmaNG",
    "EnigmaNG",
    "",
    "EnigmaNG",
    "EnigmaNG",
    "",
    "EnigmaNG",
    "",
    "EnigmaNG",
    "EnigmaNG",
    "EnigmaNG",
    "",
    "EnigmaNG",
    "",
    "EnigmaNG",
    "EnigmaNG",
#if VDRVERSNUM >= 10302
    "EnigmaNG",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "EnigmaNG",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
// END I18N - automatically generated by pot2i18n.pl
  { NULL }
};
