#!/bin/bash
###############################################################################
# This script to generate a alternative version of VDR-NG-FW from open7x0.org #
###############################################################################



###################
# Variables setup #
###################

# Path of script
BASE="${0%/*}"

# Version to generate
#   lite: Minimal install
#   pro:  Maximal install
vdr_version="pro"

# Local paths
vdr_fw="$BASE/VDR-NG-FW"
vdr_fw_orig="$vdr_fw.orig"
vdr_em_addons="$BASE/Addons"
vdr_em_files="$vdr_em_addons/Files"
vdr_em_patches="$vdr_em_addons/Patches"
vdr_em_delete="$vdr_em_addons/Delete"
vdr_em_plugins="$BASE/VDR-Plugins/Source+patch"

# SVN branch from assembla VDR-EM
svn_em="http://svn.assembla.com/svn/VDR-M7x0/unstable"

# SVN branches from open7x0.org
svn_o7o="svn://open7x0.org/uclibc_build_env/branches/experimental"

# Path for temporal directory
tmp=`mktemp -d ./tmp-XXXXXXXXXX` || exit 1


#########################
# Update/Checkout files #
#########################

# Update/Checkout VDR-EM
if [[ -d "$BASE/.svn" ]]
then
	echo "Update VDR-EM"
	svn update -q
else
	rm -f "$BASE/make-fw"
	rm -rf "$tmp"
	echo "Checkout VDR-EM"
	svn checkout -q "$svn_em" "$BASE"
	echo "Run this script again"
	exit 0
fi

# Update/Checkout VDR-o7o
if [[ -d "$vdr_fw_orig/.svn" ]]
then
	echo "Update VDR-o7o original"
	svn update -q -r 373 "$vdr_fw_orig"
else
	echo "Checkout VDR-o7o original"
	svn checkout -q -r 373 "$svn_o7o" "$vdr_fw_orig"
fi


############################
# Creating VDR-EM Firmware #
############################

# Copy original files to temporal dir
echo "Copying files to temporal dir"
cp -Trf "$vdr_fw_orig" "$tmp"
cp -Trf "$vdr_em_files/common" "$tmp"
cp -Trf "$vdr_em_files/$vdr_version" "$tmp"
cp -rf "$tmp/buildin/base-gambler/m740"  "$tmp/buildin/base-$vdr_version"
cp -rf "$tmp/buildin/base-gambler/m750s" "$tmp/buildin/base-$vdr_version"

# Patch firmware
echo "Patching Firmware"
$tmp/patches/patch-kernel.sh "$tmp" "$vdr_em_patches/common"
$tmp/patches/patch-kernel.sh "$tmp" "$vdr_em_patches/$vdr_version"

# Copy temporal dir to final dir
echo ""

if [[ -d "$vdr_fw" ]]
then
	echo "Cleaning VDR-o7o final"
	( cd $vdr_fw; make distclean )
	rm  -f $vdr_fw/*.ofi
	rm -rf $vdr_fw/buildin/base-$vdr_version
	rm -rf $vdr_fw/make-incs
	rm -rf $vdr_fw/patches
	rm -rf $vdr_fw/prg-fw-configs
	rm -rf $vdr_fw/rootfs-file-lists
	rm -rf $vdr_fw/build/vdr-m7x0-PLUGINS-extra
else
	mkdir -p "$vdr_fw"
fi

echo "Copying temporal dir to final dir"
cp -Trf "$tmp" "$vdr_fw"
mkdir -p "$vdr_fw/build/vdr-m7x0-PLUGINS-extra"
cp -Trf "$vdr_em_plugins" "$vdr_fw/build/vdr-m7x0-PLUGINS-extra"

# Delete files and dirs
echo ""
for delete in `cat "$vdr_em_delete/common.lst" | tr -d '\r' `; do
	if [ -e $delete ] ; then
		echo "Delete" $delete
		rm -rf $delete
	fi
done
for delete in `cat "$vdr_em_delete/$vdr_version.lst" | tr -d '\r' `; do
	if [ -e $delete ] ; then
		echo "Delete" $delete
		rm -rf $delete
	fi
done

# Clean temp dir
rm -rf "$tmp"
echo ""
echo ""
echo "Now you can edit config files in \"$vdr_fw\" and later run \"make\""
echo ""
exit 0
