#!/bin/sh

vdr_fw=VDR-NG-FW

vdr=$vdr_fw/build/vdr-m7x0/branches/gambler-unstable
vdr_patches=VDR-EM-files/VDR-Patches

vdr_plugins=$vdr_fw/build/vdr-m7x0-PLUGINS/branches/unstable
vdr_plugins_patches=VDR-Plugins/Source+patch

vdr_em_files=VDR-EM-files/uclibc_build_env
vdr_em_patches=VDR-EM-files/FW-Patches

webif=$vdr_fw/build/webif

#tmp=`mktemp -d ./temp.$$.XXXXXXXX` || exit 1
tmp=temp

# Update VDR-EM
echo "Update VDR-EM"
svn update

# Update VDR-NG FW
if [[ ! -d "$vdr_fw" ]]
then
	echo "Checkout $vdr_fw"
	svn checkout -q "svn://open7x0.org/uclibc_build_env/branches/experimental" "$vdr_fw"

	# Patching files of firmware
	patch -p0 -d $vdr_fw/configs/busybox/1.6.1 < $vdr_em_patches/busybox.config.diff
	patch -p0 -d $vdr_fw/buildin/usbautomounter < $vdr_em_patches/usbautomounter.diff

	# No download patchs
	patch -p0 -d $vdr_fw/make-incs < $vdr_em_patches/vdr-m7x0.mk.diff
	patch -p0 -d $vdr_fw/make-incs < $vdr_em_patches/vdr-m7x0-plugins.mk.diff
	patch -p0 -d $vdr_fw/make-incs < $vdr_em_patches/webif.mk.diff

	# Checkout VDR
	echo "Checkout $vdr"
	svn checkout -q "svn://open7x0.org/vdr-m7x0/branches/gambler-unstable" "$vdr"

	echo "Patching VDR"
	./patching ./$vdr $vdr_patches

	# Checkout open7x0.org plugins
	echo "Checkout $vdr_plugins"
        rm -rf $vdr_plugins
	mkdir -p $vdr_plugins
	svn checkout -q "svn://open7x0.org/vdr-m7x0-PLUGINS/branches/unstable" "$vdr_plugins"
	rm -rf "$vdr_plugins/sharedlibs"

	# Checkout webif
	echo "Checkout $webif"
	svn checkout -q "svn://open7x0.org/vdr-htdocs/branches/testing" "$webif"

	# Spanish translation for webif
	patch -p1 -d $webif/webapp/inc < $vdr_em_patches/webif-spanish.diff

	for dp in `ls $vdr_plugins_patches `; do
		if [ -d $vdr_plugins_patches/$dp ] ; then
			for dps in `ls $vdr_plugins_patches/$dp/`; do
				if [ -d $vdr_plugins_patches/$dp/$dps ] ; then
				        dptarget=`echo $dps | cut -d'-' -f1`

				        # Clean patch
				        rm -rf $vdr_plugins/$dptarget/
					mkdir $vdr_plugins/$dptarget/

				        # Copy plugin
					cp -rf $vdr_plugins_patches/$dp/$dps/* $vdr_plugins/$dptarget/
					find $vdr_plugins/$dptarget/ '(' -name '.svn'  ')' -exec rm -rf {} \; 2> /dev/null

					# Patching plugins
					./patching $vdr_plugins/$dptarget/ $vdr_plugins_patches/$dp
				fi
			done
		fi
	done;

	# Setup of firmware
	echo "Setup"
	rm -rf "$tmp"
	mkdir -p "$tmp"
	cp -rf $vdr_em_files/* $tmp/
	find $tmp/ '(' -name '.svn'  ')' -exec rm -rf {} \; 2> /dev/null
	cp -rf $tmp/* $vdr_fw/
	cp -rf $vdr_em_files/.config $vdr_fw/
	rm -rf "$tmp"
fi

# Compiling firmware
#cd $vdr_fw
#make
