#!/bin/sh

vdr=VDR-NG

# Update VDR-NG from SVN
if [[ ! -d "$vdr" ]]
then
	echo "CHECKOUT: $vdr"
	svn checkout -q "svn://open7x0.org/vdr-m7x0/branches/gambler-unstable" "$vdr"
fi

# Patching VDR
if [[ ! -f "$vdr/HISTORY-liemikuutio" ]]
then
	./patching ./VDR-NG ./VDR-EM-files/VDR-Patches
fi

# Compiling VDR
( cd $vdr; make )

if [[ -x $vdr/vdr ]]
then
    cp -p $vdr/vdr .
    mips-linux-uclibc-strip vdr
fi
