/*
 * i18n.c: Internationalization
 *
 * See the README file for copyright information and how to reach the author.
 *
 * $Id: i18n.c 481 2005-06-02 00:12:13Z udo $
 */

#include "i18n.h"

#if VDRVERSNUM < 10507
const tI18nPhrase StreamplayerPhrases[] = {
// START I18N - automatically generated by po2i18n.pl
  { "<no date available>",
    "<kein Datum vorhanden>",
    "",
    "",
    "",
    "",
    "<pas de date disponible>",
    "",
    "",
    "",
    "<Fecha no disponible>",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "<no description available>",
    "<keine Beschreibung vorhanden>",
    "",
    "",
    "",
    "",
    "<pas de déscriptif disponible>",
    "",
    "",
    "",
    "<Descripción no disponible>",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "<no title available>",
    "<kein Titel vorhanden>",
    "",
    "",
    "",
    "",
    "<pas de titre disponible>",
    "",
    "",
    "",
    "<Título no disponible>",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Can't download RSS stream!",
    "Kann den RSS-Stream nicht laden!",
    "",
    "",
    "",
    "",
    "Impossible de charger le flux!",
    "",
    "",
    "",
    "¡Error descargando datos RSS!",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Can't parse RSS stream!",
    "Kann den RSS-Stream nicht parsen!",
    "",
    "",
    "",
    "",
    "Impossible d'analyser le flux RSS!",
    "",
    "",
    "",
    "¡Error leyendo datos RSS!",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "HTTP proxy server",
    "HTTP Proxy Name",
    "",
    "",
    "",
    "",
    "Nom du proxy HTTP",
    "",
    "",
    "",
    "Servidor proxy HTTP",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Hide main menu entry",
    "Hauptmenüeintrag verstecken",
    "",
    "",
    "",
    "",
    "Cacher le menu",
    "",
    "",
    "",
    "Ocultar entrada en menú principal",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Hide non-existent elements",
    "Nur vorhandene Elemente zeigen",
    "",
    "",
    "",
    "",
    "N'afficher que les éléments existants",
    "",
    "",
    "",
    "Ocultar elementos vacíos",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Loading RSS stream...",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cargando elemento RSS...",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "RSS Reader",
    "RSS-Reader",
    "",
    "",
    "",
    "",
    "Lecteur de flux RSS",
    "",
    "",
    "",
    "Lector RSS",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "RSS Reader for OSD",
    "RSS-Reader für OSD",
    "",
    "",
    "",
    "",
    "Lecteur RSS pour OSD",
    "",
    "",
    "",
    "Lector RSS para OSD",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "RSS item",
    "RSS-Artikel",
    "",
    "",
    "",
    "",
    "Article RSS",
    "",
    "",
    "",
    "Artículo RSS",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Select RSS item",
    "Auswahl RSS-Artikel",
    "",
    "",
    "",
    "",
    "Choix de article RSS",
    "",
    "",
    "",
    "Seleccione artículo RSS",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Select RSS stream",
    "Auswahl RSS-Stream",
    "",
    "",
    "",
    "",
    "Choix des flux RSS",
    "",
    "",
    "",
    "Seleccione fuente RSS",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Unknown error!",
    "Unbekannt Fehler!",
    "",
    "",
    "",
    "",
    "Erreur inconnue",
    "",
    "",
    "",
    "¡Error desconocido!",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Use HTTP proxy server",
    "HTTP Proxy benutzen",
    "",
    "",
    "",
    "",
    "Utiliser le Proxy HTTP",
    "",
    "",
    "",
    "Usar servidor proxy HTTP",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
// END I18N - automatically generated by po2i18n.pl
  { NULL }
  };
#endif
