/*
 * i18n.c: 'EnigmaNG' skin for the Video Disk Recorder
 *
 * See the README file for copyright information and how to reach the author.
 *
 *
 * Translations submitted by:
 *  - English:    Andreas Mair <andreas _@_ vdr-developer.org>
 *  - Deutsch:    Andreas Mair <andreas _@_ vdr-developer.org>
 *  - Italiano:   Gringo <vdr-italian _@_ tiscali.it>
 *  - Nederlands: Johan Schuring <dorpsgek @vdr-portal.de>
 *  - Français:   Patrice Staudt <pat @vdr-portal.de>
 *  - Finnish:    Rolf Ahrenberg <rofafor @vdr-portal.de>
 *  - Polski:     ???
 *  - Español:    bittor from open7x0.org <bittor7x0 _at_ gmail.com>
 *  - Svenska:    ???
 *  - Russian:    SergArb @vdr-portal.de / neptunvasja @vdr-portal.de
 *  - Eesti:      ???
 *  - Dansk:      ???
 *  - Czech:      ???
 *  - Türkçe:     n/a
 *
 */

#include "common.h"
#include "i18n.h"

#if VDRVERSNUM < 10507
const tI18nPhrase Phrases[] = {
// START I18N - automatically generated by po2i18n.pl
  { "  Blink pause (ms)",
    "  Blink-Pause (ms)",
    "",
    "  Pausa lampeggiante (ms)",
    "  Blinkpauze (ms)",
    "",
    "  Pause de clignotement (ms)",
    "",
    "  Vilkutuksen tauko (ms)",
    "",
    "  Pausa del parpadeo (ms)",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Identify channel by",
    "  Kanal-Identifikation durch",
    "",
    "  Identifica canale per",
    "  Identificeer kanaal door",
    "",
    "  Identifier chaîne par",
    "",
    "  Tunnista kanava",
    "  Rozpoznaj kana³ po",
    "  Identificar el canal por",
    "",
    "  Identifiera kanal med",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "  ¾ßàÕÔÕÛïâì ÚÐÝÐÛ ßÞ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "  Kanali tuvastamise meetod",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Image format",
    "  Bildformat",
    "",
    "  Formato immagine",
    "  Beeldformaat",
    "",
    "  Format d'image",
    "",
    "  Kuvaformaatti",
    "",
    "  Formato de imagen",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "  ÄÞàÜÐâ Ø×ÞÑàÐÖÕÝØï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Image height",
    "  Bildhöhe",
    "",
    "  Altezza immagine",
    "  Beeldhoogte",
    "",
    "  Hauteur",
    "",
    "  Kuvien korkeus",
    "",
    "  Altura de imagen",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "  ²ëáÞâÐ Ø×ÞÑàÐÖÕÝØï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Image width",
    "  Bildbreite",
    "",
    "  Larghezza immagine",
    "  Beeldbreedte",
    "",
    "  Largeur",
    "",
    "  Kuvien leveys",
    "",
    "  Anchura de imagen",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "  ÈØàØÝÐ Ø×ÞÑàÐÖÕÝØï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Resize images",
    "  Bildberechnung benutzt",
    "",
    "  Ridimensiona immagini",
    "  Aanpassen beeldgrootte",
    "",
    "  Redimensionne les images",
    "",
    "  Muokkaa kuvien kokoa",
    "",
    "  Redimensionar imágenes",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "  ¿ÕàÕàÕèÐâì ØáßÞÛì×ãï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scoll behaviour",
    "  Scroll-Verhalten",
    "",
    "  Modalità scorrimento",
    "  Scroll gedrag",
    "",
    "  Comportement de défilement",
    "",
    "  Vieritystapa",
    "",
    "  Comportamiento del scroll",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scroll OSD title",
    "  OSD Titel scrollen",
    "",
    "  Scorri titolo OSD",
    "  OSD titel scrollen",
    "",
    "  Défilement dans le titre du OSD",
    "",
    "  Vieritä valikon otsikkoa",
    "",
    "  Título OSD del scroll",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scroll active list items",
    "  Aktive Listenzeile scrollen",
    "",
    "  Scorri elenco valori attivi",
    "  Lijst aktieve punten scrollen",
    "",
    "  Barre de défilement dans la liste active",
    "",
    "  Vieritä aktiivista valintaa",
    "",
    "  Scroll para la lista activa",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scroll delay (ms)",
    "  Scroll-Verzögerung (ms)",
    "",
    "  Ritardo scorrimento (ms)",
    "  Scrollvertraging (ms)",
    "",
    "  Délai de défilement (ms)",
    "",
    "  Vierityksen viive (ms)",
    "",
    "  Retardo del scroll (ms)",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scroll info area",
    "  Infobereich scrollen",
    "",
    "  Scorri info area",
    "  Infobereik scrollen",
    "",
    "  Barre de défilement dans la surface info",
    "",
    "  Vieritä infoaluetta",
    "",
    "  Scroll para el área info",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scroll other items",
    "  Andere Bereiche scrollen",
    "",
    "  Scorri altri valori",
    "  Andere punten scrollen",
    "",
    "  Barre de défilement dans d'autres parties",
    "",
    "  Vieritä muita alueita",
    "",
    "  Scroll para otros datos",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Scroll pause (ms)",
    "  Scroll-Pause (ms)",
    "",
    "  Pausa scorrimento (ms)",
    "  Scrollpause (ms)",
    "",
    "  Pause de défilement (ms)",
    "",
    "  Vierityksen tauko (ms)",
    "",
    "  Pausa del scroll (ms)",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show WSS mode symbols",
    "  Symbol für WSS Modus",
    "",
    "  Mostra simboli mod. WSS",
    "WSS modus symbolen tonen",
    "",
    " Afficher mode symboles WSS",
    "",
    "  Näytä WSS-symbolit",
    "",
    "  Mostrar símbolos modo WSS",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show flags",
    "  Fahnen anzeigen",
    "",
    "  Mostra segni",
    "  Vlaggen tonen",
    "",
    "  Afficher drapeau",
    "",
    "  Näytä liput",
    "",
    "  Mostrar banderas",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "  ¿ÞÚÐ×Ðâì äÛÐÓØ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show mail icon",
    "  Zeige Mail-Icon",
    "",
    "  Mostra icona email",
    "  Mail-ikoon tonen",
    "",
    "  Afficher l'icône courriel",
    "",
    "  Näytä sähköpostikuvake",
    "",
    "  Mostrar icono correo",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "  ¿ÞÚÐ×Ðâì ×ÝÐçÞÚ íÛÕÚâ. ßÞçâë",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show symbols in audio",
    "  Symbole bei Audio",
    "",
    "  Mostra simboli audio",
    "  Symbolen bij audio tonen",
    "",
    "  dans audio",
    "",
    "  Näytä symbolit äänivalikossa",
    "",
    "  Mostrar símbolos en audio",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show symbols in menu",
    "  Symbole im Menü",
    "",
    "  Mostra simboli menu",
    "  Symbolen in menu tonen",
    "",
    "  dans le menu",
    "",
    "  Näytä symbolit valikossa",
    "",
    "  Mostrar símbolos en menú",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "  ¿ÞÚÐ×Ðâì áØÜÒÞÛë Ò ÜÕÝî",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show symbols in messages",
    "  Symbole bei den Meldungen",
    "",
    "  Mostra simboli messaggi",
    "  Symbolen bij berichten tonen",
    "",
    "  dans les messages",
    "",
    "  Näytä symbolit viesteissä",
    "",
    "  Mostrar símbolos en mensajes",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "  Show symbols in replay",
    "  Symbole bei der Wiedergabe",
    "",
    "  Mostra simboli esecuzione",
    "  Symbolen bij weergave tonen",
    "",
    "  dans lecture",
    "",
    "  Näytä symbolit toistettaessa",
    "",
    "  Mostrar símbolos en reproducción",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "*** Invalid Channel ***",
    "*** Ungültiger Kanal ***",
    "",
    "*** Canale non valido ***",
    "*** Ongeldig Kanaal ***",
    "",
    "*** Chaîne non valable ***",
    "",
    "*** Virheellinen kanava ***",
    "",
    "*** Canal no válido ***",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "*** ½ÕßàÐÒØÛìÝëÙ ÚÐÝÐÛ ***",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Animated Text",
    "Bewegter Text",
    "",
    "Testo animato",
    "Geanimeerde tekst",
    "",
    "Texte défilant",
    "",
    "Tekstien elävöinti",
    "",
    "Texto animado",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Auxiliary information",
    "Zusatzinformation",
    "",
    "Informazione ausiliare",
    "Hulp informatie",
    "",
    "Information auxiliare",
    "",
    "Lisätiedot",
    "Informacje pomocnicze",
    "Información adicional",
    "",
    "Extrainformation",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ÀÐáè. ØÝäÞàÜÐæØï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Lisainfo",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Button$Flush cache",
    "Cache leeren",
    "",
    "Pulisci cache",
    "Cache legen",
    "",
    "Supprimer cache",
    "",
    "Tyhjennä",
    "Opró¿nij cache",
    "Limpiar caché",
    "",
    "Töm cachen",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¾çØáâØâì ÚÕè",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Tühjenda",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Button$Set",
    "Ändern",
    "",
    "Imposta",
    "Veranderen",
    "",
    "Changer",
    "",
    "Aseta",
    "",
    "Cambiar",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Channel logo cache size",
    "Größe des Logo-Caches",
    "",
    "Dim. cache logo canale",
    "Kanaallogo cache",
    "",
    "Taille du cache des logos",
    "",
    "Välimuistin koko kanavalogoille",
    "Rozmiar cache dla logo kana³u",
    "Tamaño de caché para los logos",
    "",
    "Cachestorlek för logotyper",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ÀÐ×ÜÕà ÚÕèÐ ÛÞÓoâØßÞÒ ÚÐÝÐÛÞÒ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Kanalilogo vahemälu suurus",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Channel:",
    "Kanal:",
    "",
    "Canale:",
    "Kanaal:",
    "",
    "Chaîne:",
    "",
    "Kanava:",
    "",
    "Canal:",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Channelinfo: language",
    "Kanalinfo: Sprache",
    "",
    "Info canale: lingua",
    "Kanaalinfo: taal",
    "",
    "Chaîne info: langue",
    "",
    "Kanavatieto: kieli",
    "",
    "Info canal: idioma",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Channelinfo: subtitle",
    "Kanalinfo: Untertitel",
    "",
    "Info canale: sottotitolo",
    "Kanaalinfo: ondertitel",
    "",
    "Chaîne info: sous-titres",
    "",
    "Kanavatieto: ohjelman kuvaus",
    "",
    "Info canal: subtítulo",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Channelinfo: title",
    "Kanalinfo: Titel",
    "",
    "Info canale: titolo",
    "Kanaalinfo: titel",
    "",
    "Chaîne info: titre ",
    "",
    "Kanavatieto: ohjelman nimi",
    "",
    "Info canal: título",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Date",
    "Datum",
    "",
    "Data",
    "Datum",
    "",
    "Date",
    "",
    "Päiväys",
    "",
    "Fecha",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Default Fixed Size Font",
    "Std. Schrift mit fester Breite",
    "",
    "Car. dim. fissa pred.",
    "Standaardwaarde font",
    "",
    "Largeur fixe standard",
    "",
    "tasavälinen kirjasintyyppi",
    "",
    "Fuente tamaño fijo defecto",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Default OSD Font",
    "Std. OSD Font",
    "",
    "Car. OSD pred.",
    "Standaard OSDfont",
    "",
    "OSD standard",
    "",
    "oletuskirjasintyyppi",
    "",
    "Fuente OSD defecto",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Default Small Font",
    "Std. kleine Schrift",
    "",
    "Car. piccolo pred.",
    "Standaard klein font",
    "",
    "Petite police standard",
    "",
    "pieni kirjasintyyppi",
    "",
    "Fuente pequeña defecto",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Details: date",
    "Details: Datumszeile",
    "",
    "Dettagli: data",
    "Details: datum",
    "",
    "Détails: date",
    "",
    "Lisätiedot: päivämäärä",
    "",
    "Detalles: fecha",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Details: subtitle",
    "Details: Untertitel",
    "",
    "Dettagli: sottotitolo",
    "Details: ondertitel",
    "",
    "Détails: Sous-titre",
    "",
    "Lisätiedot: ohjelman kuvaus",
    "",
    "Detalles: subtítulo",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Details: text",
    "Details: Text",
    "",
    "Dettagli: testo",
    "Details: tekst",
    "",
    "Détails: Texte",
    "",
    "Lisätiedot: leipäteksti",
    "",
    "Detalles: texto",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Details: title",
    "Details: Titel",
    "",
    "Dettagli: titolo",
    "Details: titel",
    "",
    "Détails: Titre",
    "",
    "Lisätiedot: ohjelman nimi",
    "",
    "Detalles: título",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Dynamic OSD size",
    "Dynamische OSD-Größe",
    "",
    "Dimensione OSD dinamica",
    "Dynamische OSD grootte",
    "",
    "Taille dynamique de OSD",
    "",
    "Mukauta kuvaruutunäytön kokoa",
    "",
    "Tamaño OSD dinámico",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPGSearch",
    "EPGSearch",
    "",
    "EPGSearch",
    "EPGsearch",
    "",
    "Recherche EPG",
    "",
    "EPGSearch",
    "",
    "EPGSearch",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Enable",
    "Verwenden",
    "",
    "Abilita",
    "Toelaten",
    "",
    "Permettre",
    "",
    "Käytä elävöintiä",
    "",
    "Activar",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EnigmaNG",
    "EnigmaNG",
    "",
    "EnigmaNG",
    "EnigmaNG",
    "",
    "EnigmaNG",
    "",
    "EnigmaNG",
    "EnigmaNG",
    "EnigmaNG",
    "",
    "EnigmaNG",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "EnigmaNG",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "EnigmaNG",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EnigmaNG skin",
    "EnigmaNG Oberfläche",
    "",
    "Interfaccia EnigmaNG",
    "EnigmaNG skin",
    "",
    "Skin EnigmaNG",
    "",
    "EnigmaNG-ulkoasu",
    "Skin EnigmaNG",
    "Piel EnigmaNG",
    "",
    "EnigmaNG-temat",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "EnigmaNG áÚØÝ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "EnigmaNG kest",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Fixed Font",
    "Schrift mit fester Breite",
    "",
    "Carattere fisso",
    "Vaste waarde font",
    "",
    "Police avec une largeur fixe",
    "",
    "Tasavälinen kirjasintyyppi",
    "",
    "Fuente Fija",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Flushing channel logo cache...",
    "Logo-Cache wird geleert...",
    "",
    "Pulizia cache logo canale...",
    "Kanaallogo cache legen...",
    "",
    "Suppression du cache...",
    "",
    "Tyhjennetään välimuistia...",
    "Opró¿niam cache logo kana³u...",
    "Limpiando la caché...",
    "",
    "Tömmer cachen...",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¾çØéÐî ÚÕè...",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Kanalilogo vahemälu tühjendamine...",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Fonts",
    "Fonts",
    "",
    "Caratteri",
    "Fonts",
    "",
    "Les polices",
    "",
    "Kirjasintyypit",
    "",
    "Fuentes",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Free last line",
    "freie letzte Zeile",
    "",
    "Ultima riga libera",
    "Vrije laatste lijn",
    "",
    "Dernière ligne libre",
    "",
    "alimmalla vapaalla rivillä",
    "",
    "Última línea libre",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Friday",
    "Freitag",
    "Petek",
    "Venerdì",
    "Vrijdag",
    "Sexta",
    "Vendredi",
    "Fredag",
    "Perjantai",
    "Pi±tek",
    "Viernes",
    "ÐáñáóêåõÞ",
    "Fredag",
    "Vineri",
    "Péntek",
    "Divendres",
#if VDRVERSNUM >= 10302
    "¿ïâÝØæÐ",
#endif
#if VDRVERSNUM >= 10307
    "Petak",
#endif
#if VDRVERSNUM >= 10313
    "Reede",
#endif
#if VDRVERSNUM >= 10316
    "Fredag",
#endif
#if VDRVERSNUM >= 10342
    "Pátek",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Full title width",
    "Volle Titelbreite",
    "",
    "Lunghezza titolo completo",
    "Volle titelbreedte",
    "",
    "Largeur totale pour le titre",
    "",
    "Levitä otsikkopalkki",
    "",
    "Ancho completo para título",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿ÞÛÝÐï èØàØÝÐ ×ÐÓÞÛÞÒÚÐ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "General",
    "Allgemein",
    "",
    "Generale",
    "Algemeen",
    "",
    "Généralité",
    "",
    "Yleiset",
    "",
    "General",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Help buttons",
    "Hilfe Tasten",
    "",
    "Tasti aiuto",
    "Help knoppen",
    "",
    "Button aide",
    "",
    "värinäppäinrivillä",
    "",
    "Botones de ayuda",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Help keys",
    "Farb-Tasten",
    "",
    "Tasti aiuto",
    "Help toetsen",
    "",
    "Touche couleur",
    "",
    "Värinäppäimet",
    "",
    "Botones de ayuda",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Info area: timers text",
    "Infobereich: Timer Text",
    "",
    "Info area: testo timer",
    "Infobereik: Timertekst",
    "",
    "Barre d'information: Text programmation",
    "",
    "Infoalue: ajastimen leipäteksti",
    "",
    "Área info: texto programación",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Info area: timers title",
    "Infobereich: Timer Titel",
    "",
    "Info area: titoli timer",
    "Infobereik: Timertitel",
    "",
    "Barre d'information: Titre Progammation",
    "",
    "Infoalue: ajastimen otsikko",
    "",
    "Área info: título programación",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Info area: warning text",
    "Infobereich: Warnung Text",
    "",
    "Info area: testo avviso",
    "Infobereik: waarschuwing tekst",
    "",
    "Barre d'information: texte d'avertissement",
    "",
    "Infoalue: varoituksen leipäteksti",
    "",
    "Área info: texto aviso",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Info area: warning title",
    "Infobereich: Warnung Titel",
    "",
    "Info area: titolo avviso",
    "Infobereik: waarschuwing titel",
    "",
    "Barre d'information: avertissement titre",
    "",
    "Infoalue: varoituksen otsikko",
    "",
    "Área info: título aviso",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Languages",
    "Sprachen",
    "",
    "Lingue",
    "Talen",
    "",
    "Langues",
    "",
    "Kielet",
    "Jêzyki",
    "Idiomas",
    "",
    "Språk",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "Ï×ëÚØ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Keeled",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Last line",
    "Letzter Zeile",
    "",
    "Ultima riga",
    "Laatste lijn",
    "",
    "Dernière ligne",
    "",
    "alimmalla rivillä",
    "",
    "Última línea",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "List items",
    "Listen",
    "",
    "Elenco valori",
    "Lijsten",
    "",
    "Liste",
    "",
    "Listat",
    "",
    "Listado",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Logos & Symbols",
    "Logos & Symbole",
    "",
    "Loghi e simboli",
    "Logo's & Symbolen",
    "",
    "Logos et symboles",
    "",
    "Logot ja symbolit",
    "",
    "Logos y símbolos",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "»ÞÓÞâØßë & áØÜÒÞÛë",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Messages",
    "Meldungen",
    "",
    "Messaggi",
    "Meldingen",
    "",
    "Message",
    "",
    "Viestit",
    "",
    "Mensajes",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Monday",
    "Montag",
    "ponedeljek",
    "Lunedì",
    "maandag",
    "Segunda",
    "Lundi",
    "Manday",
    "Maanantai",
    "poniedzia³ek",
    "Lunes",
    "ÄåõôÝñá",
    "Måndag",
    "Luni",
    "Hétfõ",
    "Dilluns",
#if VDRVERSNUM >= 10302
    "¿ÞÝÕÔÕÛìÝØÚ",
#endif
#if VDRVERSNUM >= 10307
    "Ponedjeljak",
#endif
#if VDRVERSNUM >= 10313
    "Esmaspäev",
#endif
#if VDRVERSNUM >= 10316
    "Mandag",
#endif
#if VDRVERSNUM >= 10342
    "Pondìlí",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Mute",
    "Stumm",
    "",
    "Muto",
    "Geluid uit",
    "Muet",
    "Silence",
    "",
    "Mykistetty",
    "",
    "Silenciar",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "²ëÚÛ.×ÒãÚ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Name",
    "Name",
    "",
    "Nome",
    "Naam",
    "",
    "Nom",
    "",
    "Nimi",
    "",
    "Nombre",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "No TTF support!",
    "TTF nicht unterstützt!",
    "",
    "Nessun supporto TTF!",
    "TTF niet ondersteund!",
    "",
    "Les polices TrueType ne sont pas supportées!",
    "",
    "Ei TrueType-kirjasintyyppi tukea!",
    "",
    "¡Sin soporte TTF!",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "No TrueType fonts installed!",
    "Keine TrueType Schriften installiert!",
    "",
    "Nessun carattere TrueType installato!",
    "Geen TrueType fonten geinstalleerd!",
    "",
    "Il n'y a pas de police TrueType d'installé!",
    "",
    "TrueType-kirjasintyyppejä ei löydy!",
    "",
    "¡Ninguna fuente TrueType instalada!",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "No timer check",
    "Ohne Überwachung",
    "",
    "Nessuna verifica timer",
    "Geen controle",
    "",
    "Sans surveillance",
    "",
    "Ei valvontaa",
    "",
    "No comprobar programación",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Number of Reruns",
    "Anzahl Wiederholungen",
    "",
    "Numero di repliche",
    "aantal herhalingen",
    "",
    "Nombre de répétitions",
    "",
    "Uusintojen lukumäärä",
    "",
    "Número de repeticiones",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ºÞÛØçÕáâÒÞ ßÞÒâÞàÕÝØÙ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "OSD title",
    "OSD Titel",
    "",
    "Titolo OSD",
    "OSD titel",
    "",
    "Titre OSD",
    "",
    "Valikon otsikko",
    "",
    "Título OSD",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "RERUNS OF THIS SHOW",
    "WIEDERHOLUNGEN",
    "",
    "REPLICHE DI QUESTO SPETTACOLO",
    "HERHALINGEN",
    "",
    "REPETITION",
    "",
    "TOISTUVAT TAPAHTUMAT",
    "",
    "REPETICIONES",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿¾²Â¾Àµ½¸Ï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Replay: times",
    "Wiedergabe: Zeiten",
    "",
    "Riproduzione: volte",
    "Weergave: tijden",
    "",
    "Rejouer : périodes",
    "",
    "Toisto: kellonajat",
    "",
    "Reproducir: veces",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Saturday",
    "Samstag",
    "Sobota",
    "Sabato",
    "Zaterdag",
    "Sábado",
    "Samedi",
    "Lørdag",
    "Lauantai",
    "Sobota",
    "Sábado",
    "ÓÜââáôï",
    "Lördag",
    "Sâmbãtã",
    "Szombat",
    "Dissabte",
#if VDRVERSNUM >= 10302
    "ÁãÑÑÞâÐ",
#endif
#if VDRVERSNUM >= 10307
    "Subota",
#endif
#if VDRVERSNUM >= 10313
    "Laupäev",
#endif
#if VDRVERSNUM >= 10316
    "Lørdag",
#endif
#if VDRVERSNUM >= 10342
    "Sobota",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Search pattern:",
    "Suchmuster:",
    "",
    "Modello di ricerca:",
    "Zoekpatroon:",
    "",
    "Modèle de recherche",
    "",
    "Hakutapa:",
    "",
    "Buscar patrón:",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show VPS",
    "VPS anzeigen",
    "",
    "Mostra VPS",
    "VPS tonen",
    "",
    "Afficher le VPS",
    "",
    "Näytä VPS-tieto",
    "",
    "Mostrar VPS",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì VPS",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show auxiliary information",
    "Zusatzinfo anzeigen",
    "",
    "Mostra info ausiliare",
    "Toon hulp informatie",
    "",
    "Afficher informations auxiliaires",
    "",
    "Näytä lisätiedot",
    "Pokazuj informacje pomocnicze",
    "Mostrar información adicional",
    "",
    "Visa extrainformation",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì àÐáè. ØÝäÞàÜÐæØî",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Lisainfo näitamine",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show channel logos",
    "Kanal-Logos anzeigen",
    "",
    "Mostra loghi canali",
    "Toon kanaallogo's",
    "",
    "Afficher logos des chaînes",
    "",
    "Näytä kanavalogot",
    "Pokazuj logo kana³u",
    "Mostrar logos de los canales",
    "",
    "Visa kanallogotyper",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì ÛÞÓÞ ÚÐÝÐÛÞÒ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Kanalilogo näitamine",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show event/recording images",
    "Bilder in EPG/Aufnahmendetails",
    "",
    "Mostra immagini evento/reg.",
    "Voorstelling/opname figuren tonen",
    "",
    "Images dans les EPG et détails d'enregistrements",
    "",
    "Näytä kuvat lisätietovalikossa",
    "",
    "Mostrar imágenes grabación/suceso",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¸×ÞÑàÐÖÕÝØï Ò EPG",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show info area in main menu",
    "Infobereich im Hauptmenü",
    "",
    "Mostra area info nel menu",
    "Info in hoofdmenu",
    "",
    "Surface d'infos dans le menu principal",
    "",
    "Näytä infoalue päävalikossa",
    "",
    "Mostrar info en menú principal",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì ØÝä. ÞÑÛÐáìâ Ò ÓÛ. ÜÕÝî",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show marker in lists",
    "Symbol vor Listeneinträgen",
    "",
    "Mostra indicatore elenchi",
    "Markering in lijsten tonen",
    "",
    "Marque devant les listes",
    "",
    "Näytä valintasymboli",
    "",
    "Mostrar marcador en listas",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì ÜÕâÚã Ò áßØáÚÐå",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show messages in menu on",
    "Meldungen im Menü über",
    "",
    "Mostra messaggi nel menu",
    "Toon berichten in menu aan",
    "",
    "Afficher les messages dans le menu",
    "",
    "Näytä viestit valikossa",
    "",
    "Mostrar mensajes en el menú",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show progressbar",
    "Fortschrittbalken anzeigen",
    "",
    "Mostra barra avanzamento",
    "Progressiebalk tonen",
    "",
    "Afficher barre de progression",
    "",
    "Näytä aikajana",
    "Pokazuj pasek postêpu",
    "Mostrar barra de progreso",
    "",
    "Visa framsteg",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì ØÝÔØÚÐâÞà ßàÞÔÒØÖÕÝØï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Edenemisriba näitamine",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show recording's size",
    "Aufnahmengröße anzeigen",
    "",
    "Mostra dimensione reg.",
    "Opnamegrootte tonen",
    "",
    "Afficher la taille des enregistrements",
    "",
    "Näytä tallenteen koko",
    "",
    "Mostrar tamaño de grabación",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì àÐ×ÜÕàë ×ÐßØáÕÙ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show remaining/elapsed time",
    "Zeige abgel./restl. Zeit",
    "",
    "Mostra tempo rimasto/trascorso",
    "Toon resterend/gedane tijd",
    "",
    "Afficher le temps écoulé/restant",
    "",
    "Näytä tapahtuman aika",
    "",
    "Mostrar tiempo restante/transcurrido",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì ÞáâÐÒ./ßàÞèÕÔ. ÒàÕÜï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show status symbols",
    "Statussymbole anzeigen",
    "",
    "Mostra simboli stato",
    "Status symbolen tonen",
    "",
    "Afficher symbole de status",
    "",
    "Näytä symbolit",
    "Pokazuj symbole",
    "Mostrar símbolos de estado",
    "",
    "Visa symboler",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì áØÜÒÞÛë",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Sümbolite näitamine",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show symbols",
    "Symbole anzeigen",
    "",
    "Mostra simboli",
    "Symbolen tonen",
    "",
    "Afficher symbole",
    "",
    "Näytä symbolit",
    "Pokazuj symbole",
    "Mostrar símbolos",
    "",
    "Visa symboler",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì áØÜÒÞÛë",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "Sümbolite näitamine",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show symbols in lists",
    "Symbole in Listen",
    "",
    "Mostra simboli elenchi",
    "Symbolen in lijsten tonen",
    "",
    "Symboles dans les listes",
    "",
    "Näytä tapahtumien symbolit",
    "",
    "Mostrar símbolos en listas",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×ëÒÐâì áØÜÒÞÛë Ò áßØáÚÐå",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Show timer conflicts",
    "Timerkonflikte anzeigen",
    "",
    "Mostra conflitti timer",
    "Timerconflict tonen",
    "",
    "Afficher les conflits de programmation",
    "",
    "Näytä päällekkäiset ajastimet",
    "",
    "Mostrar conflictos de programación",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿ÞÚÐ×Ðâì ÚÞÝäÛØÚâë âÐÙÜÕàÞÒ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Size",
    "Größe",
    "",
    "Dim.",
    "Grootte",
    "",
    "Taille",
    "",
    "Koko",
    "",
    "Tamaño",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ÀÐ×ÜÕà",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Sunday",
    "Sonntag",
    "Nedelja",
    "Domenica",
    "Zondag",
    "Domingo",
    "Dimanche",
    "Søndag",
    "Sunnuntai",
    "Niedziela",
    "Domingo",
    "ÊõñéáêÞ",
    "Söndag",
    "Duminicã",
    "Vasárnap",
    "Diumenge",
#if VDRVERSNUM >= 10302
    "²ÞáÚàÕáÕÝìÕ",
#endif
#if VDRVERSNUM >= 10307
    "Nedjelja",
#endif
#if VDRVERSNUM >= 10313
    "Pühapäev",
#endif
#if VDRVERSNUM >= 10316
    "Søndag",
#endif
#if VDRVERSNUM >= 10342
    "Nedìle",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "TIMERS",
    "TIMER",
    "",
    "TIMER",
    "TIMER",
    "",
    "PROGRAMMATION",
    "",
    "AJASTIMET",
    "",
    "PROGRAMACIONES",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "Â°¹¼µÀË",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Thursday",
    "Donnerstag",
    "èetrtek",
    "Giovedì",
    "Donderdag",
    "Quinta",
    "Jeudi",
    "Torsdag",
    "Torstai",
    "Czwartek",
    "Jueves",
    "ÐÝìðôç",
    "Torsdag",
    "Joi",
    "Csütörtök",
    "Dijous",
#if VDRVERSNUM >= 10302
    "ÇÕâÒÕàÓ",
#endif
#if VDRVERSNUM >= 10307
    "Èetvrtak",
#endif
#if VDRVERSNUM >= 10313
    "Neljapäev",
#endif
#if VDRVERSNUM >= 10316
    "Torsdag",
#endif
#if VDRVERSNUM >= 10342
    "Ètvrtek",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Timer check",
    "Überwachung",
    "",
    "Verifica timer",
    "Monitoren",
    "",
    "Observation de la programmation",
    "",
    "Ajastimien valvonta",
    "",
    "Comprobar programación",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿àÞÒÕàÚÐ âÐÙÜÕàÞÒ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Timer conflict",
    "Timerkonflikt",
    "",
    "Conflitto timer",
    "Timerconflict",
    "",
    "Conflit de programmation",
    "",
    "Päällekkäinen ajastin",
    "",
    "Conflicto de programación",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ºÞÝäÛØÚâ âÐÙÜÕàÐ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Timer conflicts",
    "Timerkonflikte",
    "",
    "Conflitti timer",
    "Timerconflicten",
    "",
    "Conflits de programmation",
    "",
    "Päällekkäisiä ajastimia",
    "",
    "Conflictos de programación",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ºÞÝäÛØÚâë âÐÙÜÕàÞÒ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "TrueType Font",
    "TrueType Schrift",
    "",
    "Car. TrueType",
    "TrueType Font",
    "",
    "TrueType",
    "",
    "TrueType-kirjasin",
    "",
    "Fuente TrueType",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Try 8bpp single area",
    "Einen 8bpp Bereich versuchen",
    "",
    "Prova area singola a 8bpp",
    "Op 8bpp bereik testen",
    "",
    "Essayer une surface à 8bpp",
    "",
    "Suosi yhtä 8bpp kuva-aluetta",
    "",
    "Probar un área de 8bpp",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Tuesday",
    "Dienstag",
    "Torek",
    "Martedì",
    "Dinsdag",
    "Terça",
    "Mardi",
    "Tirsday",
    "Tiistai",
    "Wtorek",
    "Martes",
    "Ôñßôç",
    "Tisdag",
    "Marþi",
    "Kedd",
    "Dimarts",
#if VDRVERSNUM >= 10302
    "²âÞàÝØÚ",
#endif
#if VDRVERSNUM >= 10307
    "Utorak",
#endif
#if VDRVERSNUM >= 10313
    "Teisipäev",
#endif
#if VDRVERSNUM >= 10316
    "Tirsdag",
#endif
#if VDRVERSNUM >= 10342
    "Úterý",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Use Subtitle for reruns",
    "Verw. Untertitel für Wdh.",
    "",
    "Utilizza sottotitolo per repliche",
    "Gebr. ondertitlel voor herh.",
    "",
    "Utilise sous-titres pour les répétitions",
    "",
    "Käytä lyhyttä kuvausta uusinnoille",
    "",
    "Usar subtítulo para repeticiones",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¸áßÞÛì×. ßÞÔ×ÐÓÞÛÞÒÚØ ÔÛï ßÞÒâÞàÕÝØï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Volume",
    "Lautstärke",
    "",
    "Volume",
    "Volume",
    "",
    "Volume",
    "",
    "Äänenvoimakkuus",
    "",
    "Volumen",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "³àÞÜÚÞáâì",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "WARNING",
    "WARNUNG",
    "",
    "ATTENZIONE",
    "WAARSCHUWING",
    "",
    "ATTENTION",
    "",
    "VAROITUS",
    "",
    "AVISO",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "¿Àµ´Ã¿Àµ¶´µ½¸µ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Wednesday",
    "Mittwoch",
    "sreda",
    "mercoledì",
    "woensdag",
    "Quarta",
    "Mercredi",
    "Onsday",
    "Keskiviikko",
    "¶roda",
    "Miércoles",
    "ÔåôÜñôç",
    "Onsdag",
    "Miercuri",
    "Szerda",
    "Dimecres",
#if VDRVERSNUM >= 10302
    "ÁàÕÔÐ",
#endif
#if VDRVERSNUM >= 10307
    "Srijeda",
#endif
#if VDRVERSNUM >= 10313
    "Kolmapäev",
#endif
#if VDRVERSNUM >= 10316
    "Onsdag",
#endif
#if VDRVERSNUM >= 10342
    "Støeda",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Width",
    "Weite",
    "",
    "Ampiezza",
    "Breedte",
    "",
    "Largeur",
    "",
    "Leveys",
    "",
    "Anchura",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "always",
    "immer",
    "",
    "sempre",
    "Altijd",
    "",
    "toujours",
    "",
    "aina",
    "",
    "siempre",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ÒáÕÓÔÐ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "data",
    "ID",
    "",
    "dati",
    "data",
    "",
    "Donnée",
    "",
    "tiedoista",
    "parametry",
    "datos",
    "",
    "data",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ÔÐÝÝëÜ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "andmed",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "elapsed",
    "abgelaufene",
    "",
    "trascorso",
    "gedane",
    "",
    "écoulé",
    "",
    "kulunut",
    "",
    "transcurrido",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ØáâÕÚèØÕ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "en_US",
    "de_DE",
    "sl_SI",
    "it_IT",
    "nl_NL",
    "pt_PT",
    "fr_FR",
    "no_NO",
    "fi_FI",
    "pl_PL",
    "es_ES",
    "el_GR",
    "sv_SE",
    "ro_RO",
    "hu_HU",
    "ca_AD",
#if VDRVERSNUM >= 10302
    "ru_RU",
#endif
#if VDRVERSNUM >= 10307
    "hr_HR",
#endif
#if VDRVERSNUM >= 10313
    "et_EE",
#endif
#if VDRVERSNUM >= 10316
    "da_DK",
#endif
#if VDRVERSNUM >= 10342
    "cs_CZ",
#endif
#if VDRVERSNUM >= 10502
    "tr_TR",
#endif
  },
  { "if exists",
    "wenn vorhanden",
    "",
    "se esiste",
    "wanneer aanwezig",
    "",
    "si existant",
    "",
    "jos olemassa",
    "",
    "si existe",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ÕáÛØ Ò ÝÐÛØçØØ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "left and right",
    "links und rechts",
    "",
    "sinistra e destra",
    "links en rechts",
    "",
    "gauche et droite",
    "",
    "edestakaisin",
    "",
    "izquierda y derecha",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "min",
    "min",
    "",
    "min",
    "min",
    "",
    "min",
    "",
    "min",
    "min",
    "min",
    "",
    "min",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ÜØÝ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "min",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "name",
    "Name",
    "",
    "nome",
    "naam",
    "",
    "Nom",
    "",
    "nimestä",
    "nazwa",
    "nombre",
    "",
    "namn",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ÝÐ×ÒÐÝØî",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "nimi",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "never",
    "nie",
    "",
    "mai",
    "nooit",
    "",
    "jamais",
    "",
    "ei koskaan",
    "",
    "nunca",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ÝØÚÞÓÔÐ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "only if new mail present",
    "nur bei neuer Mail",
    "",
    "solo se presenti nuove email",
    "alleen bij nieuwe mail",
    "",
    "juste lors d'un courriel",
    "",
    "jos uutta postia",
    "",
    "sólo si hay nuevo correo",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "âÞÛìÚÞ ßàØ ÝÞÒÞÜ áÞÞÑéÕÝØØ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "percent",
    "Prozent",
    "",
    "percentuale",
    "procent",
    "",
    "Pourcentage",
    "",
    "prosentti",
    "",
    "porcentaje",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ßàÞæÕÝâ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "pixel algo",
    "Pixel-Algorithmus",
    "",
    "algoritmo pixel",
    "pixelalgoritme",
    "",
    "Algorithme pixel",
    "",
    "näytteistys",
    "",
    "Algoritmo píxel",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ÐÛÓÞàØâÜ ßØÚáÕÛï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "ratio algo",
    "Ratio-Algorithmus",
    "",
    "algoritmo medio",
    "algoritmeratio",
    "",
    "Algorithme ratio",
    "",
    "skaalaus",
    "",
    "Algoritmo ratio",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ÐÛÓÞàØâÜ áÞÞâÝÞèÕÝØï",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "remaining",
    "restliche",
    "",
    "rimasto",
    "resterend",
    "",
    "restant",
    "",
    "jäljellä oleva",
    "",
    "restante",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ÞáâÐÛìÝëÕ",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "to the left",
    "nach links",
    "",
    "verso la sinistra",
    "naar links",
    "",
    "vers la gauche",
    "",
    "vasemmalle",
    "",
    "a la izquierda",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "use size.vdr only",
    "nur size.vdr verwenden",
    "",
    "usa solo size.vdr",
    "alleen size.vdr gebruiken",
    "",
    "utiliser seulement size.vdr",
    "",
    "vain jos size.vdr",
    "",
    "sólo usar size.vdr",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ØáßÞÛì×ÞÒÐâì âÞÛìÚÞ size.vdr",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "zoom image",
    "Zoomen",
    "",
    "ingrandisci immagine",
    "zoomen",
    "",
    "Agrandir image",
    "",
    "zoomaus",
    "",
    "Aumentar imagen",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "ÃÒÕÛØçØâì",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
// END I18N - automatically generated by po2i18n.pl
  { NULL }
  };
#endif
