/*
  	WARNING: automatically generated content. Changes will get lost!

    If this file is 'i18n-generated.h' then it *really* is automatically
	generated.
    If this file is 'i18n-template.h' then it is the base for the
    autogeneration of the other file.

*/

const tI18nPhrase Phrases[] = {
// START I18N - automatically generated by pot2i18n.pl
  { "Close on OK",
    "Schließen bei OK",
    "",
    "",
    "",
    "",
    "Fermer le menu sur OK",
    "",
    "",
    "",
    "Cerrar al OK",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Hide main menu entry",
    "Hauptmenüeintrag verstecken",
    "",
    "",
    "",
    "",
    "Masquer dans le menu principal",
    "",
    "",
    "",
    "Ocultar en el menú principal",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Fast browse",
    "Schnell navigieren",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Navegar rápido",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Fast browse (alt. key layout)",
    "Schnell navigieren (alt. Tastenbelegung)",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Navegar rápido (botones alt.)",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Switch timer",
    "Umschalttimer",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Programación de cambio",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Switch ... minutes before start",
    "Umschalten ... Minuten vor Start",
    "",
    "",
    "",
    "",
    "Changer ... minutes avant le début",
    "",
    "",
    "",
    "Cambiar ... minutos antes del inicio",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Switch timer added!",
    "Umschalttimer angelegt!",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "¡Añadida programación de cambio!",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Switch timer deleted!",
    "Umschalttimer gelöscht!",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "¡Borrada programación de cambio!",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "A zapping co-pilot",
    "Ein Zapping-Kopilot",
    "",
    "",
    "",
    "",
    "Co-pilote de zapping",
    "",
    "",
    "",
    "Un copiloto para el zapping",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "ZapPilot",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "ZapPilot",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
// END I18N - automatically generated by pot2i18n.pl
  { NULL }
};
