/*
  	WARNING: automatically generated content. Changes will get lost!

    If this file is 'i18n-generated.h' then it *really* is automatically
	generated.
    If this file is 'i18n-template.h' then it is the base for the
    autogeneration of the other file.

*/

const tI18nPhrase Phrases[] = {
// START I18N - automatically generated by pot2i18n.pl
  { "Fix bugs in EPG",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Corregir errores en EPG",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "RegexpChars$ abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789%~\\/?!()[]{}<>$^*.,:;-=#",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    " aáàbcçdeéèfghiíïjklmnñoóòpqrstuúüvwxyzAÁÀBCÇDEÉÈFGHIÍÏJKLMNÑOÓÒPQRSTUÚÜVWXYZ0123456789%~\\/?!()[]{}<>$^*.,:;-=#",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Button$Cancel",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cancelar",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Regular expressions",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Expresiones regulares",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Edit regular expressions.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Editar expresiones regulares.",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Character set conversions",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Conversiones conjunto de caracteres",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Edit character set conversions.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Editar conversiones conjunto de caracteres.",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPG blacklists",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Listas negras EPG",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Edit EPG blacklists.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Editar listas negras EPG.",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPG cloning",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Clonando EPG",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Edit EPG data cloning.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Editar datos clonando EPG.",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "--- EPG bugfixes ---",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "--- Corrección de errores EPG ---",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Remove quotes from ShortText",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Eliminar las comillas del texto corto",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPG bugfix level >= 1: Some channels put the ShortText in quotes and use either the ShortText or the Description field, depending on how long the string is:\n\nTitle\n\"ShortText\". Description",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nivel de corrección de errores EPG >= 1: Algunos canales ponen el Texto corto entre comillas y usan el Texto corto o la Descripción, dependiendo de la longitud de la cadena:\n\nTítulo\n\"Texto corto\". Descripción",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Move Description from ShortText",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Mover Descripción desde el Texto corto",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPG bugfix level >= 1: Some channels put the Description into the ShortText (preceded by a blank) if there is no actual ShortText and the Description is short enough:\n\nTitle\n Description",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nivel de corrección de errores EPG >= 1: Algunos canales ponen la Descripción en el Texto corto (precedido por un espacio en blanco) si no hay Texto corto y la Descripción es lo suficientemente corta:\n\nTítulo\n Descripción",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Remove repeated title from ShortText",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Eliminar título repetido del Texto corto",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPG bugfix level >= 1: Sometimes they repeat the Title in the ShortText:\n\nTitle\nTitle",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nivel de corrección de errores EPG >= 1: Algunas veces repiten el Título en el Texto corto:\n\nTítulo\nTítulo",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Remove double quotes from ShortText",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Eliminar comillas dobles del Texto corto",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPG bugfix level >= 1: Some channels put the ShortText between double quotes, which is nothing but annoying (some even put a '.' after the closing '\"'):\n\nTitle\n\"ShortText\"[.]",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nivel de corrección de errores EPG >= 1: Algunos canales ponen el Texto corto entre comillas dobles, lo cual es molesto (algunos incluso ponen un '.' después de cerrar '\"'):\n\nTítulo\n\"Texto corto\"[.]",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Remove useless formatting",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Eliminar formateado inútil",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPG bugfix level >= 2: Some channels apparently try to do some formatting in the texts, which is a bad idea because they have no way of knowing the width of the window that will actually display the text. Remove excess whitespace.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nivel de corrección de errores EPG >= 2: Algunos canales aparentemente tratan de hacer algún formateo en los textos, lo cual es una mala idea porque no tienen manera de saber el ancho de la ventana en la que se mostrará el texto. Eliminar el exceso de espacios en blanco.",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Move long ShortText to Description",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Mover Texto corto a la Descripción",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPG bugfix level >= 2: Some channels put a whole lot of information in the ShortText and leave the Description totally empty. So if the ShortText length exceeds 40, let's put this into the Description instead.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nivel de corrección de errores EPG >= 2: Algunos canales ponen una gran cantidad de información en el Texto corto y dejan la Descripción totalmente vacía. Así que si la longitud del Texto corto excede de 40, la pondremos en la Descripción.",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Prevent equal ShortText and Description",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Prevenir el mismo Texto corto y Descripción",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPG bugfix level >= 2: Some channels put the same information into ShortText and Description. In that case we delete one of them.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nivel de corrección de errores EPG >= 2: Algunos canales ponen la misma información en el Texto corto y la Descripción. En ese caso, borramos uno de ellos.",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Replace backticks with single quotes",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Reemplazar comillas invertidas con comillas simples",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPG bugfix level >= 2: Some channels use the ` (\"backtick\") character, where a ' (single quote) would be normally used. Actually, \"backticks\" in normal text don't make much sense, so let's replace them.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nivel de corrección de errores EPG >= 2: Algunos canales usan el caracter ` (\"comilla invertida\"), donde normalmente debería usarse una ' (comilla simple). Actualmente, las \"comillas invertidas\" en un texto normal no tienen mucho sentido, así que las reemplazamos.",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Fix stream component descriptions",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Corregir descripciones del stream",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "EPG bugfix level = 3: The stream components have a \"description\" field which some channels apparently have no idea of how to set correctly.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Nivel de corrección de errores EPG = 3: Los componentes del stream tienen un campo \"descripción\" que aparentemente algunos canales no saben establecerlo correctamente.",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Strip HTML entities",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Quitar entidades HTML",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Convert HTML entities from all fields to matching regular characters.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Convertir entidades HTML de todos los campos para coincidir con caracteres normales.",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Button$Load",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cargar",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Button$Clear EPG",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Limpiar EPG",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Loading configuration files...",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Cargando archivos de configuración...",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Clearing EPG data...",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Limpiando datos de la EPG...",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
  { "Help",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Ayuda",
    "",
    "",
    "",
    "",
    "",
#if VDRVERSNUM >= 10302
    "",
#endif
#if VDRVERSNUM >= 10307
    "",
#endif
#if VDRVERSNUM >= 10313
    "",
#endif
#if VDRVERSNUM >= 10316
    "",
#endif
#if VDRVERSNUM >= 10342
    "",
#endif
#if VDRVERSNUM >= 10502
    "",
#endif
  },
// END I18N - automatically generated by pot2i18n.pl
  { NULL }
};
