#!/bin/ash

{
# Kill VDR
/usr/bin/kill-vdr

# Umount disks
/sbin/usbautomounter umount nofsck nolazy

# Mount disks with fsck
/sbin/usbautomounter mount fsck

# Start VDR
/usr/bin/start-vdr
} > /dev/null 2>&1 &
