#!/bin/sh

directorio=$(grep "vdr_videodirs=" /etc/rc.local.conf |cut -d "=" -f2|cut -d'"' -f2)
for i in $(find $directorio -iname *.mpg -o -iname *.mpeg); do
        mpgdir=$(basename $i|sed -e 's/.[mM][pP][gG]//g' -e 's/.[mM][pP][eE][gG]//g')
        subdir=$(date -Iseconds|sed -e 's/T/./g' -e 's/:/./g' -e 's/+.*//g').99.rec
	if [ ! -d $directorio/$mpgdir ]; then 
	        mkdir -p $directorio/$mpgdir/$subdir
        	ln -s $i $directorio/$mpgdir/$subdir/001.vdr
		cd $directorio/$mpgdir/$subdir
	        genindex
        	cd $directorio
	fi
done
touch .update
